### ISSUE TITLE
Support `EXISTS (subquery)` operator

### ISSUE THREAD

**Issue by MuhannadAlrusayni** [SeaQL/sea-query#118]
Hi, I'm trying to do simple query and use `EXISTS (subquery)` operator, but it looks it's not supported yet in `sea-query`.

.e.g:
```sql
select exists(select 1 from accounts where email = $1 limit 1) as "exists!"
```

**Comment by tyt2y3** [comment]
I think it can be done like 

```rust
Query::select().expr(Expr::cust("COUNT(*) AS count")).from_subquery(...);
```

**Comment by MuhannadAlrusayni** [comment]
Yeah that's work too, but I'm not sure about the query performance `count()` vs `exists(). I'm no expert in query performance things.

And I think we should have `exists()` sooner or later.

**Comment by penso** [comment]
+1 on having `exists()`

**Comment by ikrivosheev** [comment]
I will look at the issue

**Comment by ikrivosheev** [comment]
Hello! I create PR: https://github.com/SeaQL/sea-query/issues/118.
