### ISSUE TITLE
Custom type support in Postgres

### ISSUE THREAD

**Issue by nicoulaj** [SeaQL/sea-query#131]
I am trying to support for columns using postgres enums, eg:
```
CREATE TYPE my_enum AS ENUM ( 'Variant1', 'Variant2', 'Variant3' );
```

I tried to use `Value::String` when implementing traits, but postgres will not automatically cast string values to the custom type:
```
error: cannot cast type text to my_enum
```

An explicit cast is required for bound parameters, eg:
```
insert into foo (bar) values (?::my_enum)
```
or:
```
insert into foo (bar) values (CAST(? AS my_enum))
```

So it seems a new `Value::Custom` variant is required so that we can provide the database type...

**Comment by tyt2y3** [comment]
I think the `CAST AS` way is more doable.
At least it is a lesser change to the library, as the `my_enum` is stored in the syntax tree, instead of on the `Value` itself.

**Comment by nicoulaj** [comment]
The `?::<type>` syntax is just postgres specific syntactic sugar: https://www.postgresql.org/docs/13/sql-expressions.html#SQL-SYNTAX-TYPE-CASTS

**Comment by tyt2y3** [comment]
@nicoulaj what do you think about the changes?

**Comment by nicoulaj** [comment]
I think it is great, thanks! 

I am not sure how this will be used in SeaORM though ? To use a new type in SeaORM, you implement `Nullable`, `Into<Value>`, `ValueType` and `TryGetable`.

So it seems to me `Value` is the right place to specify the cast type ?

**Comment by tyt2y3** [comment]
Well, at least it's the first step. I think the SeaORM should be able to know the `Type` of a particular `Value`, either from `ColumnDef` or a piece of metadata alongside `Value`.

**Comment by Acidic9** [comment]
Adding a generic to `Value<V>` (`Value::Custom(Option<Box<V>>)`) is a rabbit hole I've gone down a twice and spent a lot of hours on. Value is connected to everything in SeaORM, and it ends up adding generics everywhere in the project. It's a huge headache :/

I can't figure out another solution for it though..

**Comment by nicoulaj** [comment]
As discussed on the chat, what about just adding a `Value::StringCastAs(String, String)` variant ? Then it seems to me all is needed is to do a special case and add the cast here: https://github.com/SeaQL/sea-query/blob/master/src/prepare.rs#L27 ?

**Comment by tyt2y3** [comment]
It's tempting, but not ideal. Any value can be casted as any other type, not just strings.

So it's a responsibility that belongs to one level higher.

**Comment by Acidic9** [comment]
I tried creating a new type `StringCasted(String, String)` with a variant on Value `StringCastAs(Option<Box<StringCasted>>)`, but the issue is when you try to implement sqlx's [Type trait](https://docs.rs/sqlx/0.5.7/sqlx/trait.Type.html). What is the type name?
The [`fn type_info()`](https://docs.rs/sqlx/0.5.7/sqlx/trait.Type.html#tymethod.type_info) does not take Self, so it cannot be a dynamic type name :/
