### ISSUE TITLE
Support `SKIP LOCKED` for `SelectStatement`

### ISSUE THREAD

**Issue by Stumblinbear** [SeaQL/sea-query#142]
I'm working on implementing a job queue using Postgres, and I need to be able to add `SKIP LOCKED` to my select queries

**Comment by tyt2y3** [comment]
Is it an extension to https://github.com/SeaQL/sea-query/pull/117

**Comment by Stumblinbear** [comment]
Actually, no, I don't think so. With Postgres, all you need to do is add SKIP LOCKED onto a SELECT query, and it'll skip any row currently locked by a transaction. So all I have to do is: `DELETE FROM "jobs" WHERE "jobs"."id" = (SELECT "id" FROM "jobs" WHERE "execute_at" < $1 ORDER BY "id" ASC FOR UPDATE SKIP LOCKED LIMIT 1) RETURNING "type_of", "data"` inside of a transaction, do the work, then commit the transaction. Any other server looking for jobs will skip over any currently running jobs, and if the transaction fails or the client gets disconnected, the row gets unlocked.

I'm currently using the transaction branch (even with the lifetime issue (which I haven't run into), it's working great).
