### ISSUE TITLE
Support window functions

### ISSUE THREAD

**Issue by ikrivosheev** [SeaQL/sea-query#174]
Hello, thank you very match for very useful library! 

I find issue and read the comment: https://github.com/SeaQL/sea-query/issues/15#issuecomment-825363312. 
Please, can you add support for window functions.

**Comment by ikrivosheev** [comment]
I'll try to prepare PR in a couple of days

**Comment by billy1624** [comment]
Hi @ikrivosheev, thanks in advance!!

**Comment by Sytten** [comment]
I guess there was not any progress on that?
I happen to need `COUNT(*) OVER () AS count`

**Comment by ikrivosheev** [comment]
@Sytten I apologize for the long delay! I'll make PR to the end of the week

**Comment by Sytten** [comment]
No worries at all! I was just checking, we all have busy lives 😃
Looking forward to the PR.

**Comment by billy1624** [comment]
Hey @ikrivosheev, no worries! Thank you so much! :)
