### ISSUE TITLE
Ability to alter foreign keys

### ISSUE THREAD

**Issue by oscartbeaumont** [SeaQL/sea-query#184]
Hello,
Currently, using sea-query you are able to add a foreign key during table creation but I do not see any solution to do the same when altering a table.

This could be fixed by adding the method `add_foreign_key` and `delete_foreign_key` to the struct [`TableAlterStatement`](https://docs.rs/sea-query/0.18.2/sea_query/table/struct.TableAlterStatement.html).

With guidance, I could attempt a PR but I am not super familiar with the inner workings of the library.

**Comment by billy1624** [comment]
Hey @oscartbeaumont, are you looking for [this](https://docs.rs/sea-query/0.18.2/sea_query/foreign_key/struct.ForeignKeyDropStatement.html)?

**Comment by oscartbeaumont** [comment]
The [`ForeignKeyDropStatement`](https://docs.rs/sea-query/0.18.2/sea_query/foreign_key/struct.ForeignKeyDropStatement.html) and [`ForeignKeyCreateStatement`](https://docs.rs/sea-query/0.18.2/sea_query/foreign_key/struct.ForeignKeyCreateStatement.html) is exactly what I want except my issue is how can I run them against a real database. By my understanding a `add_foreign_key` and `delete_foreign_key` function would have to be added to the struct [`TableAlterStatement`](https://docs.rs/sea-query/0.18.2/sea_query/table/struct.TableAlterStatement.html) so that it can be executed like every other table update instruction.

I'm sure I could convert the [`ForeignKeyDropStatement`](https://docs.rs/sea-query/0.18.2/sea_query/foreign_key/struct.ForeignKeyDropStatement.html) and [`ForeignKeyCreateStatement`](https://docs.rs/sea-query/0.18.2/sea_query/foreign_key/struct.ForeignKeyCreateStatement.html) to a SQL string and run it against the database but that seems unnecessarily wierd.

**Comment by billy1624** [comment]
Ah okay, got what you mean. So, you can build querying like...

```sql
alter table active_enum
    add constraint active_enum_applog_id_fk_0
        foreign key (id) references applog (id),
    add constraint active_enum_applog_id_fk_1
        foreign key (id) references applog (id);
```

```sql
alter table active_enum
    drop foreign key active_enum_applog_id_fk_0,
    drop foreign key active_enum_applog_id_fk_1;
```

> This could be fixed by adding the method `add_foreign_key` and `delete_foreign_key` to the struct [`TableAlterStatement`](https://docs.rs/sea-query/0.18.2/sea_query/table/struct.TableAlterStatement.html).

Yes, we can
