### ISSUE TITLE
No SchemaTableColumn

### ISSUE THREAD

**Issue by rex-remind101** [SeaQL/sea-query#199]
I'd like to refer to a column but schema such as `schema.table.column` but this doesn't seem possible. https://github.com/SeaQL/sea-query/blob/eca4ece31e18e8cefb5a14def38b75605df17504/src/types.rs#L62 only has `Column` and `TableColumn` but no `SchemaTableColumn`.

Please add :)

**Comment by billy1624** [comment]
Hi @rex-remind101, welcome!!

Yes, It's currently missing and we could add that. Would you like to create a PR for it? I point you the direction.

**Comment by rex-remind101** [comment]
yes please, thank you

**Comment by billy1624** [comment]
Add a new variant `SchemaTableColumn(DynIden, DynIden, DynIden)` to 
https://github.com/SeaQL/sea-query/blob/ff10e85baa15b1081f034a8aa0efde8846aa1a6b/src/types.rs#L60-L65

Then, `impl IntoColumnRef for (S, T, C)`.

Finally, compile it and you should see the final thing you need to update, aka the schema builder.

**Comment by masimons** [comment]
@billy1624 sure, how can a PR be opened?
