### ISSUE TITLE
Inserting Json values

### ISSUE THREAD

**Issue by Follpvosten** [SeaQL/sea-query#20]
I'm currently trying to insert into a table, and I'm hitting this panic: https://github.com/SeaQL/sea-query/blob/7a2331a1d5e81f9c907dd71189ab8e1828c0743f/src/value.rs#L164

To me it sounds like at that line, the Object should be converted to a Value::Bytes using serde_json::to_vec. I am actually not sure how that would interact with postgres' jsonb type, I think you have to create jsonb values like `'{"field":"value"}'::jsonb`. Which is a complicated problem now since this should only happen on json_binary() columns, while normal json columns should use `::json` instead...

**Comment by tyt2y3** [comment]
I am trying to support JSON values at https://github.com/SeaQL/sea-query/commit/ce7e3ee542eee8dde5352d50beec16f7dab465d9 but not sure whether it works for you.
Can you share your use case perhaps by submitting as an `example`?

**Comment by Follpvosten** [comment]
I've updated the postgres example in the values branch to use a json field: https://github.com/Follpvosten/sea-query/commit/399931378991ac8971ec97739d95be68f27f84c8

Note that I don't think this example will be suitable for inclusion in the default repo; for my usecase, I'm only using uuids (so there's no auto increment and no ids generated by postgres, I'm always inserting the whole dataset including its id, which is why I can easily use `InsertStatement::json` for inserts). But you can try the example.

The new `Value::Json` variant seems to work correctly for me, which is great; that now *almost* allows me to use InsertStatement::json again (dates are still an issue that's left, but at least json types work now, so yay).

**Comment by tyt2y3** [comment]
Please check `0.7.0` and let me know!

**Comment by tyt2y3** [comment]
https://github.com/SeaQL/sea-query/tree/master/examples/postgres_json
