### ISSUE TITLE
No Left Join Lateral

### ISSUE THREAD

**Issue by rex-remind101** [SeaQL/sea-query#201]
Hi, I've been looking for a way to perform left join lateral for Postgres but I haven't found a way to do this. Is it available?

**Comment by billy1624** [comment]
Hey @rex-remind101, thanks for the question! Currently, it's not supported :(

**Comment by rex-remind101** [comment]
Is there a way to apply raw SQL? I've tried `.expr(Expr::cust())` but it seems incorrectly place the text for the join in the select statement and appends a `,` as if it was a column.

**Comment by billy1624** [comment]
> Is there a way to apply raw SQL? I've tried `.expr(Expr::cust())` but it seems incorrectly place the text for the join in the select statement and appends a `,` as if it was a column.

Yes, I think we need to introduce a new join operator to support join lateral. Would you be interested in creating a PR? I could help if you want :P

**Comment by rex-remind101** [comment]
Sure thing 👍

**Comment by rex-remind101** [comment]
think i'll actually tackle this now. i saw you got my other issue fixed (thank you). do you have any pointers on where to start?

**Comment by billy1624** [comment]
I have never use the `LATERAL` keyword. Can you explain what select statement you want to construct?

From my understanding, both MySQL and PostgreSQL support `LATERAL` but not SQLite.
- MySQL: https://dev.mysql.com/doc/refman/8.0/en/lateral-derived-tables.html
- PostgreSQL: https://www.postgresql.org/docs/14/sql-select.html

Some sample select statements with `LATERAL`:

```sql
SELECT *
FROM table_1,
     LATERAL (SELECT * FROM tbale_2) as t2
         LEFT JOIN LATERAL (SELECT * FROM tbale_3) as t3 on 1 = 1
         LEFT JOIN LATERAL (SELECT * FROM tbale_4) as t4 on 1 = 1
WHERE 1 = 1
```

**Comment by rex-remind101** [comment]
i use `[left] join lateral` specifically to pull columns from an outer query into an inner subquery and then join. it's simpler than a strict subquery

e.g.

```sql
select
  t1.name,
  descendants.count IS NULL as is_leaf,
from t1
left join lateral (
  select ancestor, count(1) as count from t2
  where ancestor = t1.uuid group by 1
) as descendants on descendants.ancestor = t1.uuid
```

**Comment by billy1624** [comment]
So, basically we need to write the `LATERAL` keyword to the join expression.

https://github.com/SeaQL/sea-query/blob/67a8ffba1351c754aae2559051930d4fe2fe70ae/src/query/select.rs#L71-L77

Given that all types of joins support `LATERAL`.

https://github.com/SeaQL/sea-query/blob/67a8ffba1351c754aae2559051930d4fe2fe70ae/src/types.rs#L145-L152

We could just add a `bool` to `JoinExpr` indicating if it's a `LATERAL` join. Make sense? Sounds easy?

**Comment by rex-remind101** [comment]
makes sense, easy idk, will need to dive in. will work on this tomorrow, thanks :+1:

**Comment by rex-remind101** [comment]
https://github.com/SeaQL/sea-query/pull/224

**Comment by rex-remind101** [comment]
hello, i opened a pr

**Comment by billy1624** [comment]
Hey @rex-remind101, sorry for the delay. I will check that later today :)

**Comment by rex-remind101** [comment]
Hi, still waiting on review, thank you
