### ISSUE TITLE
[Question]Any way to add a return statement?

### ISSUE THREAD

**Issue by RonaldColyar** [SeaQL/sea-query#203]
Current I have a query that I would like to add a return statement to:

```
    let query = Query::insert()
        .into_table("scheduled_room_attendance")
        .columns(vec![
            "userId",
            "scheduledRoomId",
            "isOwner"])
        .values_panic(vec![
            attendance.user_id,
            attendance.scheduled_room_id,
            attendance.is_owner])
        .to_owned();
```
Is there any cascading methods used for returning the unique SERIAL id that is generated here?

**Comment by RonaldColyar** [comment]
```

    let (sql, values) = Query::insert()
        .into_table(Character::Table)
        .columns(vec![Character::Character, Character::FontSize])
        .values_panic(vec!["A".into(), 12.into()])
        .returning_col(Character::Id)
        .build(PostgresQueryBuilder);

```

This example shows sample usage.

**Comment by billy1624** [comment]
Hi @RonaldColyar, welcome!

Yes, you could do so with [`.returning()`](https://docs.rs/sea-query/0.19.2/sea_query/query/struct.InsertStatement.html#method.returning) or [`.returning_col`](https://docs.rs/sea-query/0.19.2/sea_query/query/struct.InsertStatement.html#method.returning_col).

**Comment by RonaldColyar** [comment]
@billy1624  sorry for the noise. Thanks for your amazing work!

**Comment by billy1624** [comment]
No worries! Thanks for the supports :P
