### ISSUE TITLE
Inserting Timestamp values

### ISSUE THREAD

**Issue by Follpvosten** [SeaQL/sea-query#21]
I have a chrono::NaiveDateTime value, which would translate to a TIMESTAMP in postgres as shown here: https://docs.rs/postgres/0.19.0/postgres/types/trait.ToSql.html#types

I'm having trouble understanding how I would convert it to a sea_query::Value. Alternatively I could switch to SystemTime, but that's not really gonna help me here.

**Comment by billy1624** [comment]
We could support common datetime library in Rust like `chrono`.  Converting it to `sea_query::Value`.

**Comment by tyt2y3** [comment]
Move to #23
