### ISSUE TITLE
alter table statements only seem to add a single column at a time

### ISSUE THREAD

**Issue by glommer** [SeaQL/sea-query#213]
The following code:

```
        let mut table = Table::alter()
            .table(Alias::new("table"))
            .add_column(ColumnDef::new(Alias::new("new_col"))
                .integer()
            )
            .add_column(ColumnDef::new(Alias::new("new_col2"))
                .integer()
            )
            .to_owned();
        println!("TEST {:#?}", table.to_string(sea_query::PostgresQueryBuilder));
```

Prints this:
```
TEST "ALTER TABLE \"table\" ADD COLUMN \"new_col2\" integer"
```

The first `add_column` seems to be ignored.

**Comment by billy1624** [comment]
Hey @glommer, yes, the table alter statement will alter only one column at a time. The reason behind being although MySQL and PostgreSQL both support altering multiple columns in one statement, yet SQLite does not.

**Comment by glommer** [comment]
Thanks you - as I also do want to support sqlite, it's good to keep in mind.

However this behavior is, may I say it, at least a bit tricky. Couple of considerations:
1. I was explicitly asking for a Postgres query, so why wouldn't it generate a query with many alters in this case?
2. The failure mode is silent: Some of the add columns are just ignored, and I only noticed this when a tricky bug manifested in my application due to a column not being added.

**Comment by billy1624** [comment]
> 2. The failure mode is silent: Some of the add columns are just ignored, and I only noticed this when a tricky bug manifested in my application due to a column not being added.

I have to admit this is bad.

For MySQL & PostgreSQL, we could easily supports alter multiple columns in single alter table statement.

```sql
ALTER TABLE tblName
    ADD COLUMN ColumnNameA ... ,
    ADD COLUMN ColumnNameA ... ,
    ADD COLUMN ColumnNameA ...
```

For SQLite, perhaps we can do something like this.

```sql
ALTER TABLE tblName ADD COLUMN ColumnNameA ... ;
ALTER TABLE tblName ADD COLUMN ColumnNameB ... ;
ALTER TABLE tblName ADD COLUMN ColumnNameC ... ;
```
