### ISSUE TITLE
Add WHERE EXISTS condition

### ISSUE THREAD

**Issue by RomainMazB** [SeaQL/sea-query#216]
Now that `SELECT EXISTS` may be about to get merged, the `EXISTS` as condition method should be supported too.

The `WHERE EXISTS` clause is really useful on relationship constraints:

As an example to retrieve all the game's character owned by a user with name starting by `bo`:
```sql
SELECT * FROM `characters`
WHERE EXISTS(
    SELECT * FROM `users`
    WHERE `users`.`name` LIKE "bo%"
        AND  `users`.`id` = `characters`.` user_id`
)
```

This function would accept the subquery as parameter and just add the `EXISTS`  `BinOp`, the same way `in_subquery` does.

Could tackle this tonight if this seems fine to everyone.

**Comment by billy1624** [comment]
Hey @RomainMazB,

> This function would accept the subquery as parameter and just add the `EXISTS` `BinOp`, the same way `in_subquery` does.

You mean adding it to `SimpleExpr`? I supposed

https://github.com/SeaQL/sea-query/blob/8ad6fbf668833e0a003e4a27c409ae87ea6d0bb9/src/expr.rs#L20-L38

So, we have a new variant `Exists(Box<SelectStatement>)`.

**Comment by RomainMazB** [comment]
I guess it could leave into `SubQuery(Box<SelectStatement>)`, do you see any objection to this?

It's implementation could look like this (basically a copy/paste of in_subquery function):
```rust
pub fn exists(mut self, sel: SelectStatement) -> SimpleExpr {
    self.bopr = Some(BinOper::Exists);
    self.right = Some(SimpleExpr::SubQuery(Box::new(sel)));
    self.into()
}
```

**Comment by billy1624** [comment]
Shouldn't it be a unary operator?

```sql
SELECT * FROM `characters`
WHERE
    -- this is a select statemet wrapped in EXISTS operator
    EXISTS (
        SELECT * FROM `users`
        WHERE `users`.`name` LIKE "bo%"
            AND  `users`.`id` = `characters`.` user_id`
    )
```

**Comment by RomainMazB** [comment]
I was just toying on this one, and just figured out my mistake!
Indeed we can't implement this the same way `in_subquery` is implemented because ...*suspens*... it's an unary operator.

**Comment by billy1624** [comment]
Hahaaa that's fine! We need more collaborators here loll more brain power

**Comment by RomainMazB** [comment]
I almost succeed, **but** something will be missing. You'll understand easier with the test results before:
```rust
sea_query::Query::select()
    .column(Char::Id)
    .from(Char::Table)
    .and_where(
        Expr::exists(
            Query::select()
                .from(Font::Table)
                .and_where(Expr::tbl(Char::Table, Char::FontId).equals(Font::Table, Font::Id))
                .and_where(Expr::tbl(Font::Table, Font::Variant).eq("italic"))
                .take()
        )
    )
```
![image](https://user-images.githubusercontent.com/53976837/147769776-956f6160-d22e-4e77-8392-f114e86cbf30.png)

My problem is that I'm now stuck because as you can see the subselect doesn't query any columns, obviously because I didn't pass any `Expr::col` but I don't want to, I want à wildcard `SELECT *`:
- I can't just set the `select.exists` to `Some` and rely on the other PR, because it will adds the whole `SELECT EXISTS * [...] as exists` into the subquery
- I don't have a way to "inject" my wildcard after the subquery `SELECT` keyword

```rust
SimpleExpr::UnarySelect(op, select) => {
    // Add the EXISTS keyword (or NOT EXISTS, see last line of the comment)
    self.prepare_un_oper(op, sql, collector);
    // Open parentheses, obviously
    write!(sql, " (").unwrap();
    // Generate the subselect with no columns :'(
    self.prepare_select_statement(select, sql, collector);
    // Close parentheses, ...
    write!(sql, ")").unwrap();
}
```

I may leave this one as is, and rework on it after being able to add `Expr::wildcard()`, I will publish my current work as a draft PR in few hours.

*I momentarilly named the new type `SimpleExpr::UnarySelect(UnOper, Box<SelectStatement>)` so we can still pass a different unary operator for other useful use case like `NOT EXISTS`*

**Comment by ikrivosheev** [comment]
Close with: https://github.com/SeaQL/sea-query/pull/379
