### ISSUE TITLE
Add Expr::asterisk() and Expr::tbl_asterisk(IntoTableRef)

### ISSUE THREAD

**Issue by RomainMazB** [SeaQL/sea-query#217]
In most of the case, we don't need to list all the columns of the table, which could be tedious with some large tables.

We should be able to pass an `Expr::wildcard()` or `Expr::wildcard(IntoTableRef)` to the columns' list, which would result in an asterisk or a table name followed by an asterisk:
```rust
// SELECT * FROM `character`;
Query::select()
    .expr(Expr::wildcard())
    .from(Char::Table);

// SELECT `character`.*, `glyph`.`aspect`
// FROM `character`
// JOIN `glyph` ON ....;
Query::select()
    .expr(Expr::tbl_wildcard(Char::Table))
    .columns(Glyph::Table, Glyph::Aspect)
    .from(Char::Table)
    .join(Glyph::Table, /*...*/);
```

This could also open some other doors of features like the one I stuck on here: https://github.com/SeaQL/sea-query/issues/216#issuecomment-1003102381

**Comment by tyt2y3** [comment]
I don't actually oppose this feature. Though I can imagine it could be kind of 'insecure' in some sense.

**Comment by RomainMazB** [comment]
Yeah, I see why you feel like it could be insecure, and I thought the same, but it's exactly the same than doing `Expr::expr("*")` so the insecurity is already here.

With the second one (providing the table name as `Iden`), we instead provide a way to "close" some insecurity doors: instead of providing a "table.*" as a string, we enforce the developers to set a correct table name.
