### ISSUE TITLE
Allow using prepared statements

### ISSUE THREAD

**Issue by Follpvosten** [SeaQL/sea-query#22]
The following example:

```rust
#[derive(Debug, sea_query::Iden)]
pub enum Character {
    Table,
    Id,
    Character,
    FontSize,
    SizeW,
    SizeH,
    FontId,
}

fn main() {
    use Character::{Character as Char, FontId, FontSize, Id, SizeH, SizeW};
    let stmt = sea_query::Query::insert()
        .into_table(Character::Table)
        .columns(vec![Id, Char, FontSize, SizeW, SizeH, FontId])
        .to_string(sea_query::PostgresQueryBuilder);

    println!("{}", stmt);
}
```
currently prints:
```
INSERT INTO "character" ("id", "character", "font_size", "size_w", "size_h", "font_id") VALUES 
```

To make the usage of sea-query more straightforward while it's not yet possible to use all types with `InsertStatement::values()` or `InsertStatement::json()` (see #20, #21), it would be great if it would instead yield this:
```
INSERT INTO "character" ("id", "character", "font_size", "size_w", "size_h", "font_id") VALUES ($1, $2, $3, $4, $5, $6)
```
when used with PostgresQueryBuilder (for use with the `postgres` or `tokio-postgres` crate), or respectively this:
```
INSERT INTO "character" ("id", "character", "font_size", "size_w", "size_h", "font_id") VALUES (?, ?, ?, ?, ?, ?)
```
on mysql for use with the `mysql` crate.
This could either happen automatically whenever the statement's values are empty, or explicitly using something like a `InsertStatement::values_prepared()`.

This would allow easily using the resulting string with `Client::prepare` in postgres, or respectively `Queryable::prep` in mysql, so without much effort you'd gain the ability to use all of the native types these crates can accept, as well as the ability to integrate with their way of sanitizing inputs.

If there's interest, I could contribute something like this and open a PR, but I'd need to know which way of implementing this would be the best (implicit vs explicit).

**Comment by billy1624** [comment]
Please see `InsertStatement::build()` and `InsertStatement::build_collect()`
https://docs.rs/sea-query/0.6.0/sea_query/query/struct.InsertStatement.html#method.build
https://docs.rs/sea-query/0.6.0/sea_query/query/struct.InsertStatement.html#method.build_collect

See if this is what you need :)

**Comment by Follpvosten** [comment]
> https://docs.rs/sea-query/0.6.0/sea_query/query/struct.InsertStatement.html#method.build

Thanks for pointing me to that! In the basics, this is what I need. However I would currently have to supply dummy values, since replacing the `.to_string` with `.build` in my example above (also changing `{}` to `{:?}`), the output is this:

```
("INSERT INTO \"character\" (\"id\", \"character\", \"font_size\", \"size_w\", \"size_h\", \"font_id\") VALUES ", [])
```

For this to be usable, the string would have to contain the `($1, $2, $3, $4, $5, $6)` part even when there are no values. Would that be possible/a good idea? I can of course provide 6 dummy values (like `.values_panic(vec![0.into(),0.into(),0.into(),0.into(),0.into(),0.into()])`, but if I get the count wrong, that's gonna be an issue.

**Comment by tyt2y3** [comment]
I guess the problem is to make our current Value compatible with postgres's Value type, and right now for sqlx we are using an adapter for that https://github.com/SeaQL/sea-query/blob/master/src/driver/sqlx.rs
Likewise, we can make an adapter for the postgres library too. And then we can ship it as part of the library for convenience.

**Comment by Follpvosten** [comment]
Hm. The main issue I'm seeing is that many kinds of values have to be handled in a fairly special way for postgres - for example, as I noted in #20, json values in postgres have to be suffixed by `::json` or `::jsonb` respectively. I might be missing something here, but wouldn't that require adding a new variant to Value, like `Value::Json`? Possibly two for json and jsonb. The situation is similar for postgres array types (which I will need soon).

I don't know if that wouldn't be too big of a change to just "make it compatible", it would require changes everywhere, which is why I created this issue proposing a workaround until these can be implemented. (Of course now that you pointed me to the build method, it isn't as important for me because that's already an acceptable workaround if I use dummy values.)

**Comment by tyt2y3** [comment]
Thank you for your explanation. Yes I think we can change the behavior for `INSERT INTO` but then it does not help in other queries.
In the long term, I think its nicer to do things with support from the library rather than having to workaround it. I am thinking to extend the `Value` type and support postgres'a `ToSql` behind a feature.

**Comment by Follpvosten** [comment]
I think the idea of implementing ToSql isn't bad, but note that with the current API of `build()`, you would have to collect into a second `Vec<&dyn ToSql>` (because the prepare/execute methods on postgres::Client take a `&[&dyn ToSql]`). I don't think that is fixable at all, but it's something to keep in mind and should probably at least be documented since it's not really intuitive.

**Comment by tyt2y3** [comment]
#23
