### ISSUE TITLE
Why are why you using back-ticks for sqlite identifiers instead of double quotes?

### ISSUE THREAD

**Issue by SpyrosRoum** [SeaQL/sea-query#220]
If you switch to double quotes then you avoid this sqlx [issue](https://github.com/launchbadge/sqlx/issues/1531), which would allow `RETURNING` to work for SQLite for every backend (plus you are more correct according to the SQL standard))
[SQLite keywords](https://www.sqlite.org/lang_keywords.html)

**Comment by tyt2y3** [comment]
It might not be a problem with SQLx. May be we can cross-check using Rusqlite?
Anyhow I support this change.

**Comment by SpyrosRoum** [comment]
So I run most of what's in the tests in table.rs, I checked `returning` and I checked a few `select` queries as well.
All of them seem to work fine with double quotes

**Comment by SpyrosRoum** [comment]
With this closed, the comments saying that `RETURNING` doesn't work for sqlx can be removed now.
I didn't think it was fitting to include the change in the pr but I'm happy to open a new one if you want

**Comment by tyt2y3** [comment]
@billy1624 I think you might want to close the SQLx issue

**Comment by billy1624** [comment]
> @billy1624 I think you might want to close the SQLx issue

Yes, we should
