### ISSUE TITLE
Common table expressions and `WITH RECURSIVE`

### ISSUE THREAD

**Issue by 05storm26** [SeaQL/sea-query#228]
Basically support for this: https://www.postgresql.org/docs/9.1/queries-with.html

Especially useful would be the `WITH RECURSIVE` query support. This basically allows you to do all kinds of crazy stuffs like traversing a flattened tree using standard SQL syntax, etc.

**Comment by billy1624** [comment]
Hey @05storm26, I think we can support this. The syntax of common table expressions is quite similar across all three databases.
- PostgreSQL: https://www.postgresql.org/docs/14/queries-with.html
- MySQL: https://dev.mysql.com/doc/refman/8.0/en/with.html
- SQLite: https://www.sqlite.org/lang_with.html

**Comment by 05storm26** [comment]
I am working on this.

**Comment by tyt2y3** [comment]
Thank you @05storm26 actually I have used CTE in raw SQL and I think it is quite powerful!
Can you share a bit how you imagine the final API looks like?

**Comment by billy1624** [comment]
Thanks!! @05storm26
