### ISSUE TITLE
`Value` type revamp

### ISSUE THREAD

**Issue by tyt2y3** [SeaQL/sea-query#23]
- Feature guarded
- Support protocol native types
- Connection helper

Ref:
1. https://docs.rs/sqlx/0.5.1/sqlx/mysql/types/index.html
2. https://docs.rs/sqlx/0.5.1/sqlx/postgres/types/index.html
3. https://docs.rs/postgres/0.19.0/postgres/types/trait.ToSql.html

**Comment by Follpvosten** [comment]
Note: The optional dependency for postgres should probably be on the [postgres-types crate](https://docs.rs/postgres-types/0.2.0/postgres_types/trait.ToSql.html) which is used and re-exported by both `postgres` and `tokio-postgres`

**Comment by Follpvosten** [comment]
Another note: Postgres bool columns don't take numeric inserts.

`PostgresError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42804"), message: "column \"premium\" is of type boolean but expression is of type integer", detail: None, hint: Some("You will need to rewrite or cast the expression."), position: Some(Original(237)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_target.c"), line: Some(582), routine: Some("transformAssignedExpr") })`

**Comment by tyt2y3** [comment]
@Follpvosten Please see if https://github.com/SeaQL/sea-query/blob/c5d9b59779af1a03819853a4ef9fc9a74e6ef869/examples/postgres/src/main.rs looks good?

Btw, are you using any derive macro for `From<Row>`?

**Comment by Follpvosten** [comment]
That example looks ok to me. I'm using [tokio-pg-mapper](https://crates.io/crates/tokio-pg-mapper) for deriving a kind of "FromRow" (which also doesn't panic on missing rows).

**Comment by tyt2y3** [comment]
`0.7.0`
