### ISSUE TITLE
Dynamic query construction

### ISSUE THREAD

**Issue by phungleson** [SeaQL/sea-query#230]
Hi,

I am trying to do something like this

```rust
let mut update = Query::update();

update.table(X::Table);

if let Some(attr1) = attr1 {
    update.value(X::Attr1, attr1.clone().into());
}

if let Some(attr2) = attr2 {
    update.value(X::Attr2, attr2.clone().into());
}

let (query, values) = update
    .and_where(Expr::col(X::Id).eq(id))
    .build(PostgresQueryBuilder);

let result = bind_query(sqlx::query(&query), &values)
    .execute(&mut *conn)
    .await;
```

Basically, I would like to construct the query depending if `attr1` and `attr2` are `Some` or `None`.

But I getting this error:

```
future created by async block is not `Send`

= help: within `TableRef`, the trait `std::marker::Send` is not implemented for `Rc<(dyn Iden + 'static)>`
note: future is not `Send` as this value is used across an await
```

```
   |
36 |       let mut update = Query::update();
   |           ---------- has type `UpdateStatement` which is not `Send`
...
53 |       let result = bind_query(sqlx::query(&query), &values)
   |  __________________^
54 | |         .execute(&mut *conn)
55 | |         .await;
   | |______________^ await occurs here, with `mut update` maybe used later
```

I am not sure if it is possible with `sea-query`?

**Comment by tyt2y3** [comment]
In the nutshell, the simplest way is to enable the thread-safe feature

**Comment by billy1624** [comment]
If you look into the examples. You will find similar code without needing the `thread-safe` feature enabled.

https://github.com/SeaQL/sea-query/blob/5d6ef72a4db7e8e494a297a6bf570d9a91f41262/examples/sqlx_mysql/src/main.rs#L45-L75

https://github.com/SeaQL/sea-query/blob/5d6ef72a4db7e8e494a297a6bf570d9a91f41262/examples/sqlx_mysql/Cargo.toml#L13-L20

**Comment by phungleson** [comment]
Hey @billy1624 thanks!

Maybe I am missing something here but when I look into https://github.com/SeaQL/sea-query/blob/5d6ef72a4db7e8e494a297a6bf570d9a91f41262/examples/sqlx_mysql/src/main.rs#L45-L75

I don't see how it fits into my issues, i.e. the example writing the query in a single chain where as in my case I need to break the query in multiple chains due to if conditions.

Maybe something obvious that I couldn't see?

**Comment by billy1624** [comment]
I'm not sure why this error occured. I manage to write and compile the follow code snippet. I think it has nothing to do with the condition chains.

```rust
let mut stmt = Query::update();

stmt.table(Character::Table);

let val = Some(vec![(Character::FontSize, 24.into())]);
if let Some(v) = val {
    stmt.values(v);
}
stmt.and_where(Expr::col(Character::Id).eq(id));

let (sql, values) = stmt.build(MysqlQueryBuilder);

let result = bind_query(sqlx::query(&sql), &values)
    .execute(&mut pool)
    .await;
```

**Comment by billy1624** [comment]
Would you mind showing me the toml? The line you include `sea-query` as dependency and how you define the `X` Iden.

**Comment by phungleson** [comment]
Hi @billy1624 my dependency looks like this

```
sea-query = { version = "0.20", features= ["sqlx-postgres", "postgres-uuid", "postgres-chrono", "postgres-rust_decimal"] }
```

**Comment by phungleson** [comment]
I managed to make it works after adding `"thread-safe"`

I wonder what's the performance implication?

I define `X` like this:

```
#[derive(Iden, Clone)]
pub enum X {
    Table,
    Id,
    Attr1,
    Attr2,
}

```

**Comment by billy1624** [comment]
Regarding the difference in performance, it's `Rc` vs `Arc`
- https://users.rust-lang.org/t/how-much-expensive-is-arc-vs-rc/48756

**Comment by phungleson** [comment]
Thanks, do you happen to put the code somewhere so I can take a look?

It would be good to use `Rc` if it is possible, thanks again!

**Comment by billy1624** [comment]
> Thanks, do you happen to put the code somewhere so I can take a look?

You mean where we switch the use of `Arc` and `Rc`?

https://github.com/SeaQL/sea-query/blob/9264434b8305d0bc2f4a9a9e4587def58b94e614/src/types.rs#L6-L9

**Comment by phungleson** [comment]
I mean the code you mentioned that building query dynamically is working in this comment

https://github.com/SeaQL/sea-query/issues/230#issuecomment-1012885416

**Comment by billy1624** [comment]
Oh, okay. Check this https://github.com/billy1624/sea-query/commit/6f6c0f02db9bb8109e700c2b9598f3032e91a863

**Comment by phungleson** [comment]
Awesome thanks!

I am closing this for now, will open a new one if I found something, thanks again!

**Comment by billy1624** [comment]
No problem :)

**Comment by enheit** [comment]
> I managed to make it works after adding `"thread-safe"`
> 
> I wonder what's the performance implication?
> 
> I define `X` like this:
> 
> ```
> #[derive(Iden, Clone)]
> pub enum X {
>     Table,
>     Id,
>     Attr1,
>     Attr2,
> }
> ```

Hey @phungleson, could you share your solution to this problem? I don't know where to put "thread-safe" attribute.

I have a similar issue where I want to dynamically create a query inside a loop.

It shows me an error

```
rustc: future cannot be sent between threads safely
   the trait `Send` is not implemented for `Rc<(dyn Iden + 'static)>`
   required for the cast to the object type `dyn std::future::Future<Output = Result<(), AppointmentSaveErrors>> + Send`
```

Here my code snippet

```
        let (query, values) = Query::insert()
            .into_table(DbAppointment::Table)
            .columns([
                DbAppointment::Id,
                DbAppointment::WorkingDayId,
                DbAppointment::ClientId,
                DbAppointment::SpecialistId,
                DbAppointment::StartTime,
                DbAppointment::EndTime,
                DbAppointment::Status,
            ])
            .values_panic(vec![
                appointment.id.into(),
                appointment.working_day_id.into(),
                appointment.client_id.into(),
                appointment.specialist_id.into(),
                appointment.time_slot.start_time.into(),
                appointment.time_slot.end_time.into(),
                "PENDING".into(),
            ])
            .build(PostgresQueryBuilder);

        let mut assigned_services_builder = Query::insert()
            .into_table(DbAppointmentService::Table)
            .columns([
                DbAppointmentService::Id,
                DbAppointmentService::AppointmentId,
                DbAppointmentService::Name,
                DbAppointmentService::Price,
                DbAppointmentService::Duration,
            ]);
        
        for service in appointment.services.into_iter() {
            assigned_services_builder.values_panic(vec![
                service.id.into(),
                appointment.id.into(),
                service.name.value.to_owned().into(),
                service.price.value.into(),
                service.duration.value.into(),
            ]);
        }

        let (query2, values2) = assigned_services_builder.build(PostgresQueryBuilder);
```

**Comment by phungleson** [comment]
Hey @enheit, I don't know enough but from the code, it looks like it is very straight forward and it shouldn't need `thread-safe`?

Maybe other parts of the code that might require `thread-safe`?

**Comment by billy1624** [comment]
Hey @enheit, as said on Discord.

> A workaround would be to construct the query in sync env then pass it on to async env to execute it. In this way, you don't need to enable thread-safe feature.

**Comment by enheit** [comment]
> Hey @enheit, as said on Discord.
> 
> > A workaround would be to construct the query in sync env then pass it on to async env to execute it. In this way, you don't need to enable thread-safe feature.

I followed your advice and extracted the query builder into a separate function and call it from within the `async` method. Looks like it works

**Comment by tyt2y3** [comment]
Awesome
