### ISSUE TITLE
Support Insert from Select

### ISSUE THREAD

**Issue by Sytten** [SeaQL/sea-query#231]
This is a very common syntax that is currently not supported:
```sql
INSERT INTO table SELECT ...;
```
It don't expect it is very hard to support, willing to help on it.

**Comment by billy1624** [comment]
I think this would be easy to implement.

Just want to put some references down here:
- SQLite: https://www.sqlite.org/lang_insert.html
- MySQL: https://dev.mysql.com/doc/refman/8.0/en/insert-select.html
- PostgreSQL: https://www.postgresql.org/docs/current/sql-insert.html

**Comment by 05storm26** [comment]
I am working on this.
