### ISSUE TITLE
SimpleExpr::SubQuery can only wrap `SelectStatement`s

### ISSUE THREAD

**Issue by 05storm26** [SeaQL/sea-query#240]
Maybe also allow UPDATE/DELETE RETURNING queries? 

What do you think about changing 
```rust
SubQuery(Box<SelectStatement>
```
to
```rust
SubQuery(Box<&dyn QueryStatementBuilder>
```
?

**Comment by billy1624** [comment]
I'm not sure why the change from `SubQuery(Box<SelectStatement>` to `SubQuery(Box<&dyn QueryStatementBuilder>` would enable "UPDATE/DELETE RETURNING queries"

**Comment by 05storm26** [comment]
`UpdateStatement` and `DeleteStatement` implement the `QueryStatementBuilder` meaning you can convert `Box<UpdateStatement>` and `Box<DeleteStatement>` into `Box<&dyn QueryStatementBuilder>`. Therefore you could put these into `SimpleExpr::SubQuery`.

**Comment by billy1624** [comment]
> `UpdateStatement` and `DeleteStatement` implement the `QueryStatementBuilder` meaning you can convert `Box<UpdateStatement>` and `Box<DeleteStatement>` into `Box<&dyn QueryStatementBuilder>`. Therefore you could put these into `SimpleExpr::SubQuery`.

Yeah, this make sense
