### ISSUE TITLE
Allow all types to be serializable

### ISSUE THREAD

**Issue by 05storm26** [SeaQL/sea-query#242]
Allow all of `sea_query`'s types like `SelectStatement`, `SimpleExpr`,  ... etc to be serializable and deserializable using serde.

**Comment by 05storm26** [comment]
My idea was maybe a little niche, but what I was thinking is maybe saving user generated `SimpleExpr`s into the database that are then queried from the database by the application and used in building another query. Basically creating an application that is allowing the user to customise some queries. This can currently be done by allowing any sql text and then using `SimpleExpr::Custom` but that allows any kind of text even malicious ones by injection. If you could make a UI for building a `SimpleExpr` then you could serialize that into the databse instead of a raw text.

But now that I think about it, this doesn't actually solve the injection issue. You can put together malicous queries even without `SimpleExpr::Custom` like a `SimpleExpr::SubQuery` containing a delete query etc. If you have a UI for building `SimpleExpr` then you still need to validate the expression and then build the text sql query and put that into the database as text and then use `SimpleExpr::Custom`.

So this alone doesn't save you from SQL injection, only writing validation can save you from that, and if you do that at the end you can just save the result as text and use `SimpleExpr::Custom`. 

So now that I have thought about it maybe it is not that necessary afterall.

**Comment by billy1624** [comment]
Yeah, it still suffer from the potential SQL injection :(
Interesting idea though!

**Comment by ming535** [comment]
One use case I can think of is in products like `supabase` or `postgrest` which build SQL query based on http request from the browser. It will be easier to implement feature like this if `sea_query` support `Deserialize`, since we can have the browser submit a JSON and deserialize it into `xxStatement`.

**Comment by ikrivosheev** [comment]
@ming535 I think it's very dangerous feature. Because every change of internal structs is breaking change. I'm afraid to bring this into SeaQuery.

**Comment by ikrivosheev** [comment]
I think, we can create a new library, like Django-filter or sqlalchemy-filtering to convert json objects into SeaQuery structs.
