### ISSUE TITLE
Is not possible to use chrono::DateTime<Local>

### ISSUE THREAD

**Issue by mamcx** [SeaQL/sea-query#244]
In the implementation for chrono, is not possible to directly use [DateTime<Local>](https://docs.rs/chrono/0.4.19/chrono/offset/struct.Local.html).

**Comment by billy1624** [comment]
We have `DateTimeLocal` now, added on #249

https://github.com/SeaQL/sea-query/blob/519f458fb19c633f282c32734cbe3e3731e99dba/src/value.rs#L64-L66
