### ISSUE TITLE
Add support for ORDER BY FIELD/CASE

### ISSUE THREAD

**Issue by PauMAVA** [SeaQL/sea-query#246]
In MySQL there is a `FIELD` function that can be used with `ORDER BY` to order the result in the same order as a list of elements. For example:
```sql
SELECT * FROM my_table
ORDER BY FIELD(my_col, ['USD', 'CAD', 'AUD', 'BBD', 'EUR', 'GBP'])
```
Would order the result according to the value of `my_col` being `USD` rows before `CAD` rows before `AUD`...
In Postgres and SQLite this can be achieved by using the following syntax:
```sql
ORDER BY
  CASE
    WHEN code='USD' THEN 1
    WHEN code='CAD' THEN 2
    WHEN code='AUD' THEN 3
    WHEN code='BBD' THEN 4
    WHEN code='EUR' THEN 5
    WHEN code='GBP' THEN 6
    ELSE 7
```
As a side note, this is needed in order to accomplish foreign-key marker support in `sea-orm`.

I propose that we add a new variant to the `Order` enum such as:
```rust
pub Order {
    Asc,
    Desc,
    Field((ColumnRef, Vec<DynIden>)),
}
```
Where `ColumnRef` is the column where the values belong and `Vec<DynIden>` the values to be used to order the result.

**Comment by billy1624** [comment]
Hey @PauMAVA, thanks for the help :)

I think the `ColumnRef` is not necessary, as we can get store "the column" inside `OrderExpr::expr`.

https://github.com/SeaQL/sea-query/blob/6c11e64dd7b88b994fd778a0763161a9801a7769/src/types.rs#L161-L167

Also, perhaps we can change `Field((ColumnRef, Vec<DynIden>))` into `Field(Values)`, where `Values` is a vector of values.

https://github.com/SeaQL/sea-query/blob/6c11e64dd7b88b994fd778a0763161a9801a7769/src/value.rs#L108-L109

Does this make sense?

**Comment by PauMAVA** [comment]
Yes @billy1624 , I have only one doubt.

In `OrderExpr.expr` there will be only the column name, right? I will implement this today and open a PR😄.

**Comment by billy1624** [comment]
For `OrderExpr.expr` it's of type `SimpleExpr`. Column name is one of the possible variant of it, i.e. `SimpleExpr::Column(ColumnRef)`.

https://github.com/SeaQL/sea-query/blob/6c11e64dd7b88b994fd778a0763161a9801a7769/src/expr.rs#L20-L38

**Comment by PauMAVA** [comment]
Okay. Thanks!

**Comment by billy1624** [comment]
> I will implement this today and open a PR😄.

Thanks!
