### ISSUE TITLE
add postgres distinct on please

### ISSUE THREAD

**Issue by oonxt** [SeaQL/sea-query#250]
I tried this :
Query::select()
            .expr(Expr::cust("distinct on (id)"))

 but got a comma here:
SELECT distinct on (id), "id" FROM
____________________^

https://www.postgresql.org/docs/12/sql-select.html#SQL-DISTINCT

**Comment by billy1624** [comment]
Hey @oonxt, from what I know. You can rewrite the `DISTINCT ON` with `GROUP BY`.
Checkout https://www.sea-ql.org/SeaORM/docs/advanced-query/aggregate-function

**Comment by oonxt** [comment]
ok. thx.
