### ISSUE TITLE
Add multiple columns to CommonTableExpression

### ISSUE THREAD

**Issue by Sytten** [SeaQL/sea-query#255]
Currently there is only the `column` method, you so have to write a for loop if you have a vec of columns.
I suggest we add a `columns` method that takes an IntoIterator and adds all the column.
I will push a PR tomorrow.

**Comment by Sytten** [comment]
Same would be nice for general selects too now that I think of it

**Comment by billy1624** [comment]
Hey @Sytten, yeah, that would be nice! Open for contributions! This should be an easy one :P

Proposed changes
- Adding a method similar to [`CommonTableExpression::column`](https://docs.rs/sea-query/0.21.0/sea_query/query/struct.CommonTableExpression.html#method.column) but takes iterator of `IntoIden`

**Comment by umak1106** [comment]
> Hey @Sytten, yeah, that would be nice! Open for contributions! This should be an easy one :P
> 
> Proposed changes
> - Adding a method similar to [`CommonTableExpression::column`](https://docs.rs/sea-query/0.21.0/sea_query/query/struct.CommonTableExpression.html#method.column) but takes iterator of `IntoIden`

Hello , If it is okay by you I would like to work on this issue . I hope you will guide me incase any problem arises .

**Comment by billy1624** [comment]
Hey @umak1106, thanks in advance for the contributions! Is there any updates on the status? Feel free to ping me if you need any help on it. Also, you can create a draft PR for it, even it's not ready or buggy :P

**Comment by ikrivosheev** [comment]
@umak1106 @billy1624 if no one minds, I have time to implement this.

**Comment by umak1106** [comment]
yes I don't mind @ikrivosheev

**Comment by ikrivosheev** [comment]
@umak1106 ok, i will make PR today or tomorrow.
