### ISSUE TITLE
Changing the GenericBuilder trait

### ISSUE THREAD

**Issue by emmanuelantony2000** [SeaQL/sea-query#26]
Currently the GenericBuilder train returns `Box<dyn QueryBuilder>` for `query_builder(&self)` and so on for other functions. We could use an associated type (which would be `Self` for this case) and then return the object without boxing it.

Something like this:

```rust
pub trait GenericBuilder {
    type Builder: QueryBuilder + TableBuilder + IndexBuilder + ForeignKeyBuilder;

    fn query_builder(&self) -> Self::Builder;
    fn table_builder(&self) -> Self::Builder;
    fn index_builder(&self) -> Self::Builder;
    fn foreign_key_builder(&self) -> Self::Builder;
}
```

**Comment by tyt2y3** [comment]
Thanks for the suggestion!
