### ISSUE TITLE
Allow trailing commas in all and any macros

### ISSUE THREAD

**Issue by insanitybit** [SeaQL/sea-query#268]
## Summary
Basically, it'd be nice to have trailing commas in `any!` and `all!`. The following code won't compile due to that trailing comma

```rust
sea_query::all![
    Expr::col(Node::Uid).eq(uid),
    Expr::col(Node::TenantId).eq(tenant_id),
//                                         ^ that little angel right there
]
```

I'm a novice with macros but I google'd how to do it and this looks right.

```rust
macro_rules! all {
    ( $( $x:expr ),* $(,)?) => {
        {
            let mut tmp = sea_query::Condition::all();
            $(
                tmp = tmp.add($x);
            )*
            tmp
        }
    };
}
```

All I did was add ` $(,)?` which I guess makes the last comma optional.

## Motivation

It's a really tiny, minor thing. But trailing commas make life better. I can comment out the last line, or copy/paste things around, or re-order lines, without fear.

## Additional Information

Note that the suggested approach I've provided does require rust 1.32, which I think is edition 2018. Given that this crate is 2021, there should be no risk of this change breaking anything.

**Comment by tyt2y3** [comment]
Sounds like a great idea. Can you open a PR for this?
