### ISSUE TITLE
JOIN with alias

### ISSUE THREAD

**Issue by Follpvosten** [SeaQL/sea-query#28]
Support the following:
`LEFT JOIN table AS alias`
This is already possible for fields with `expr_alias` and for the FROM clause via `from_alias`, but not for joins (as far as I can tell, would love to be proven wrong). This is important as soon as you want to JOIN the same table twice.

Note that this might require an `Expr::alias(alias, column)` as well, but not necessarily since you can just use `Expr::tbl` with an  `Alias` everywhere.

**Comment by tyt2y3** [comment]
Thank you! Would you mind if I rename the method to `join_as`?

**Comment by tyt2y3** [comment]
Thank you! Included in `0.6.1`

**Comment by Follpvosten** [comment]
Thanks!
