### ISSUE TITLE
Avoid heap allocations by using slices and references

### ISSUE THREAD

**Issue by wnmrmr** [SeaQL/sea-query#281]
## Summary

Boxes and Vecs are very common in the codebase, leading to unnecessary heap allocations

## Motivation 

Performance

## Additional Information

From what I've fiddled with, lifetime annotations will be necessary everywhere, making things less ergonomic, and may possibly break API.

Ofc, the performance improvement may be marginal or non-existent since I've not measured it.

**Comment by wnmrmr** [comment]
Sorry that was not a good idea at all

**Comment by billy1624** [comment]
Hey @wnmrmr, no worries! Thanks for making SeaQuery better!

**Comment by phungleson** [comment]
Hey @wnmrmr & @billy1624 I was having somewhat similar thoughts, just curious why that wasn't a good idea, besides like what you already said `lifetime annotations will be necessary everywhere, making things less ergonomic, and may possibly break API `.

**Comment by wnmrmr** [comment]
When I opened this issue I had the enum `sea_query::expr::SimpleExpr` in my mind, but since sea-query is dynamic, we can't know its size at compile time, so as far as I know we can't use slices and references (for the same reason we can't for arbitrary trees). But it can be a good idea 🙂

**Comment by phungleson** [comment]
Yeah it makes sense, thanks for the explanation @wnmrmr 😃

**Comment by tyt2y3** [comment]
We cannot avoid dynamic sizing, but we can avoid heap allocation by using smallvec, arraystring etc
I'd be interested how much performance it's going to improve. If someone is interested, we can probably work together on that.
