### ISSUE TITLE
question: millisecond timestamps?

### ISSUE THREAD

**Issue by jadamcrain** [SeaQL/sea-query#282]
I am using sea-query to write to TimescaleDB and am using the following column for spatial partitioning:

```
...
 timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
...
```

The representation in SQL for this type is `microsecond` precision. I only need milliseconds, but seaquery appears to only write second precision when mapping from `DateTime<Utc>`, e.g.:

'2022-03-29 18:33:24 +00:00'

Is there a way to change this default or another strategy you can suggest? Will I need to just use a string type and do my own date/time formatting?

**Comment by ikrivosheev** [comment]
@jadamcrain can you show simple example?

**Comment by jadamcrain** [comment]
Here's an example

```
use sea_query::{Iden, Query, PostgresQueryBuilder};
use std::fmt::Write;
use chrono::{Utc, DateTime};

#[derive(Debug)]
enum Measurements {
    Table,
    // columns
    Timestamp,
    Value,
}

impl Iden for Measurements {
    fn unquoted(&self, s: &mut dyn Write) {
        let text = match self {
            Measurements::Table => "measurements",
            Measurements::Timestamp => "timestamp",
            Measurements::Value => "value",
        };
        write!(s, "{}", text).unwrap()
    }
}

fn main() {
    let now : DateTime<Utc> = Utc::now();
    let parsed = DateTime::parse_from_rfc3339("1985-04-12T23:20:50.123456Z").unwrap();

    println!("parsed: {}", parsed);

    let statement = Query::insert()
        .into_table(Measurements::Table)
        .columns([
            Measurements::Timestamp,
            Measurements::Value
        ])
        .values_panic(
            [
                42.0.into(),
                now.into()
            ]
        )
        .values_panic(
            [
                23.0.into(),
                parsed.into()
            ]
        )
        .to_string(PostgresQueryBuilder);

    println!("{}", statement);
}

```

This example program prints:

```
parsed: 1985-04-12 23:20:50.123456 +00:00
INSERT INTO "measurements" ("timestamp", "value") VALUES (42, '2022-03-30 19:09:22 +00:00'), (23, '1985-04-12 23:20:50 +00:00')
```

Seaquery drops the fractional seconds when generating the statement. All of the postgres time types have 1 microsecond precision.

https://www.postgresql.org/docs/current/datatype-datetime.html

**Comment by Sytten** [comment]
Hum yeah but this example is actually misleading. In reality that data is passed down the database executor to be properly escaped at the database level, it's not the job of sea-query to do that. What you see here is just a debug representation I believe, so you need to check with whatever executor you use how they handle the DateTime.

**Comment by jadamcrain** [comment]
Ah, ok.  I've been executing the raw string against a sqlx postgresql connection.

How is `seaquery` integration supposed to work with sqlx?

**Comment by ikrivosheev** [comment]
@jadamcrain you can read examples: https://github.com/SeaQL/sea-query/blob/master/examples/sqlx_postgres/src/main.rs

**Comment by ikrivosheev** [comment]
@jadamcrain succeeded with an example?

**Comment by jadamcrain** [comment]
Will update once I've had a chance to try, but I'm sure this will do the trick.

**Comment by Sytten** [comment]
Raw string is actually vulnerable to SQL injections so you should definitely not do that. Keep us posted when you try it!
