### ISSUE TITLE
String escape doesn't work for SQLite

### ISSUE THREAD

**Issue by kylestang** [SeaQL/sea-query#294]
## Description

The [escape_string](https://github.com/SeaQL/sea-query/blob/master/src/value.rs#L1044) function replaces single quotes `'` with `\'` to insert strings into the database, which doesn't work for SQLite. Here's the relevant part of the [documentation](https://www.sqlite.org/lang_expr.html):

>  A string constant is formed by enclosing the string in single quotes ('). A single quote within the string can be encoded by putting two single quotes in a row - as in Pascal. C-style escapes using the backslash character are not supported because they are not standard SQL. 

Using `''` to escape single quotes works in MySQL, Postgres, and SQLite so it should be a pretty easy fix. I'm happy to submit a PR if people are fine with that solution.

## Steps to Reproduce

1. Using rusqlite, create a db and table with a text field.
2. Create an insert query that contains a single quote using SqliteQueryBuilder.
3. Execute the query with rusqlite and unwrap the result.

### Expected Behavior

The entry is added to the table.

### Actual Behavior

An SqliteFailure error is returned.

### Reproduces How Often

Every time.

## Versions

sea-query v0.24.0
sea-query-derive v0.2.0
sea-query-driver v0.1.0
rusqlite v0.27.0

## Additional Information

Reproducible example:

```rust
use rusqlite::Connection;
use sea_query::{ColumnDef, Iden, Query, SqliteQueryBuilder, Table};

#[derive(Iden)]
enum Foo {
    Table,
    Text,
}

fn main() {
    let db = Connection::open("my_db.sqlite").unwrap();
    
    let table = Table::create()
        .table(Foo::Table)
        .if_not_exists()
        .col(ColumnDef::new(Foo::Text).text())
        .build(SqliteQueryBuilder);

    let insert = Query::insert()
        .into_table(Foo::Table)
        .columns(vec![Foo::Text])
        .values_panic(vec!["Can't insert".into()])
        .to_string(SqliteQueryBuilder);

    db.execute(&table, []).unwrap();
    db.execute(&insert, []).unwrap(); // returns error
}
```

**Comment by ikrivosheev** [comment]
@kylestang thank you for the report! To me this looks like a good solution.

@tyt2y3 @billy1624?

**Comment by tyt2y3** [comment]
I am not sure how bad it might be, but I think we need dedicated escape and unescape functions for each backend with logic properly implemented from respective docs.

p.s. the current implementation follows `mysql_real_escape_string`.

**Comment by Sytten** [comment]
I worked a bit on escape a while ago, the PR is still up. Not sure if it is relevant.

**Comment by ikrivosheev** [comment]
@tyt2y3 the current implementation is: https://docs.rs/sea-query/latest/sea_query/value/fn.escape_string.html or do you want to move it to backend?

**Comment by ikrivosheev** [comment]
@Sytten you worked on the function: `ESCAPE`, issues is about bug, when generate query, if I understood correctly

**Comment by billy1624** [comment]
Hey @kylestang, thanks for the report!

> Using `''` to escape single quotes works in MySQL, Postgres, and SQLite so it should be a pretty easy fix. I'm happy to submit a PR if people are fine with that solution.

This is a good fix indeed! This make sense to me.

References
- https://mariadb.com/kb/en/string-literals/
- https://dev.mysql.com/doc/refman/8.0/en/string-literals.html
- https://www.sqlite.org/faq.html#q14
- https://www.postgresql.org/docs/current/sql-syntax-lexical.html

**Comment by tyt2y3** [comment]
> @tyt2y3 the current implementation is: https://docs.rs/sea-query/latest/sea_query/value/fn.escape_string.html or do you want to move it to backend?

Yes. It might be more work than necessary but I think it is the canonical way moving forward

**Comment by ikrivosheev** [comment]
@tyt2y3 might be move [`unescape_string`](https://docs.rs/sea-query/latest/sea_query/value/fn.unescape_string.html) into backend?

**Comment by ikrivosheev** [comment]
> @tyt2y3 might be move [`unescape_string`](https://docs.rs/sea-query/latest/sea_query/value/fn.unescape_string.html) into backend?

@tyt2y3 what do you think?

**Comment by tyt2y3** [comment]
> @tyt2y3 might be move [`unescape_string`](https://docs.rs/sea-query/latest/sea_query/value/fn.unescape_string.html) into backend?

Yes I agree with that

**Comment by tyt2y3** [comment]
I believe this is fixed now. Please reopen if you find other problems regarding this.
