### ISSUE TITLE
Unable to use `sea_query_driver_postgres!` macro with re-exported sqlx from another crate

### ISSUE THREAD

**Issue by sumeetattree** [SeaQL/sea-query#295]
## Description

`sea_query_driver_postgres!` macro does not recognize `sqlx` crate if consumed via a re-export from another crate.

We have a lot of internal crates so we like to reexport commonly used external crates via a single internal crate to keep the version numbers consistent between the internal crates.

Here's the minimum reproducible repository: https://github.com/sumeetattree/sea-query-reexport-min-repro

## Steps to Reproduce

1. Create 2 crates: `test-a`, and `test-common`.
2. Re-export sqlx from test-common/lib.rs
 ```rs
     pub use sqlx;
```
3. Import in `test-a`
```rs
    use test_common::sqlx;

    sea_query::sea_query_driver_postgres!();
    use sea_query_driver_postgres::bind_query;
```

### Expected Behavior

Re-exported crate should have been detected by the macro.

### Actual Behavior

An error stating that `undeclared crate sqlx` is raised.

```
error[E0433]: failed to resolve: use of undeclared crate or module `sqlx`
 --> test-project/src/handlers/handler.rs:9:1
  |
9 | sea_query::sea_query_driver_postgres!();
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `sqlx`
  |
  = note: this error originates in the macro `sea_query::sea_query_driver_postgres` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0432]: unresolved import `sqlx`
 --> test-project/src/handlers/handler.rs:9:1
  |
9 | sea_query::sea_query_driver_postgres!();
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a similar path exists: `crate::sqlx`
  |
  = note: `use` statements changed in Rust 2018; read more at <https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html>
  = note: this error originates in the macro `sea_query::sea_query_driver_postgres` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0412]: cannot find type `PgArguments` in this scope
 --> test-project/src/handlers/handler.rs:9:1
  |
9 | sea_query::sea_query_driver_postgres!();
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
  |
  = note: consider importing this struct:
          crate::sqlx::postgres::PgArguments
  = note: this error originates in the macro `sea_query::sea_query_driver_postgres` (in Nightly builds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0412, E0432, E0433.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `test-project` due to 3 previous errors
[Finished running. Exit status: 101]
```

### Reproduces How Often

Always

## Versions

```
├── sea-query v0.24.0
│   ├── sea-query-driver v0.1.0 (proc-macro) 
```
OS: Windows WSL2

**Comment by tyt2y3** [comment]
Oh, it seems to be caused by the recent change #292

**Comment by ikrivosheev** [comment]
@sumeetattree  @tyt2y3 I'm already working on a fix

**Comment by ikrivosheev** [comment]
@tyt2y3 this behavior was before the PR

**Comment by tyt2y3** [comment]
Thanks for the input ikrivosheev. @sumeetattree my recommendation that you do not use a re-export crate, but use a version = "^0" line in your Cargo.toml and let another crate in the dependency tree to pin a version

**Comment by ikrivosheev** [comment]
@sumeetattree I have done PR, you can view.

**Comment by ikrivosheev** [comment]
@tyt2y3 re-export is useful when a crate with all dependencies for project.

**Comment by sumeetattree** [comment]
@ikrivosheev this looks great! Thanks!

**Comment by sumeetattree** [comment]
@tyt2y3 @ikrivosheev any ETA on this?

**Comment by ikrivosheev** [comment]
@sumeetattree I am waiting for merge for PR

**Comment by tyt2y3** [comment]
[0.24.1](https://github.com/SeaQL/sea-query/releases/tag/0.24.1)
