### ISSUE TITLE
Procedural macros for generating a Iden enum from structs

### ISSUE THREAD

**Issue by eexsty** [SeaQL/sea-query#296]
## Summary

I recently made a crate in which it auto-generates an enum-based type definitions from structs, and I think it would be useful to have a similar feature in the official crate. I think it would be useful to also have a similar feature for creating tables and don't needing to provide all columns manually (such as a `AllColumn` helper).

I can implement this feature by myself by opening a pull request, if everyone agrees to it.

https://github.com/eexsty/squtils
**Example**
```rust
#[generate_type_def]
struct Foo {
    bar: String,
    baz: i32,
}

/// This is the same as doing:
/// struct Foo {
///    bar: String,
///    baz: i32,
/// }
/// #[derive(Iden)]
/// enum FooTypeDef {
///   Table,
///   Bar,
///   Baz
/// }
```

## Motivation

Avoid having to declare the same fields in a enum and struct, this would generate it automatically for you, this would avoid people forgetting to add field in both enum and struct.

**Comment by tyt2y3** [comment]
Thank you for your suggestion, but I think it kind of overlaps with SeaORM's DeriveEntityModel

**Comment by eexsty** [comment]
> Thank you for your suggestion, but I think it kind of overlaps with SeaORM's DeriveEntityModel

It would make queries a lot easier and reduce the amount of lines of code, so I think it would be useful to be implemented, I never used SeaORM so I didn't knew about DeriveEntityModel.

**Comment by eexsty** [comment]
https://github.com/eexsty/sea-query/blob/features/proc-macro/type-definition-generator/sea-query-attr/src/lib.rs
