### ISSUE TITLE
Provide a custom derive for Iden

### ISSUE THREAD

**Issue by Follpvosten** [SeaQL/sea-query#3]
Looking at how you have to manually implement Iden at the moment, it seems like a natural fit for a minimal derive macro.
Something like this:
```rust
#[derive(Iden)]
#[iden(rename_all = "snake_case")]
pub enum Character {
    #[iden("character")]
    Table,
    Id,
    Character,
    FontSize,
    SizeW,
    SizeH,
    FontId,
}
```

Going one step further, you could theoretically derive it on a struct as well, auto-generating the enum:

```rust
#[derive(IdenEnum, PostgresMapper)]
#[iden(table = "character")]
pub struct Character {
    id: i64,
    character: String,
    font_size: i64,
    size_w: i64,
    size_h: i64,
    font_id: Option<i64>,
}
// This would generate the enum above with an Iden implementation based on the struct's fields.
// As for the name of the enum, that could be chosen by another iden attribute, and default to
// something like {struct name}Def, ie CharacterDef.
// The implementation would transform the field names in the enum to PascalCase by default.
// And then you can directly use the struct with tokio-pg-mapper (Character::from_row)
```

This is mostly playing with ideas, but I'd be interested in contributing something like that if there is interest. Possibly something like that is already planned for SeaORM, but it would be nice to have it customizable and independent of the bigger ORM project.

**Comment by Follpvosten** [comment]
I'm currently using this workaround to reduce the boilerplate:
```rust
#[derive(serde::Serialize)]
#[serde(rename_all = "snake_case")]
pub enum UserV1 {
    Table,
    Id,
    Name,
    Email,
}

impl Iden for UserV1 {
    fn unquoted(&self, s: &mut dyn Write) {
        match self {
            Self::Table => write!(s, "user"),
            f => write!(s, "{}", serde_json::to_string(f).unwrap()),
        }
        .unwrap();
    }
}
```
But the practicality and performance of that is questionable.

If you'd be interested in me potentially contributing a proc macro like this, please tell me; I'd be happy to start working on it if it lines up with the goals of sea-query.

**Comment by tyt2y3** [comment]
SeaORM would include a code generator for these definitions so it'd be more ergonomic.
But for SeaQuery, yes it is manual and it'd be nice to ease the process a bit. I think providing macro is good as long as we don't force people into using them.
I think you nailed a smart hack! Never thought of implementing things this way.
As on performance, I think it will be fine. Becaues the internal syntax tree holds `Rc` to `Iden`, and only at the final `prepare()` step that `unquoted()` would be called. May be we can micro benchmark a bit in the end.

Yes, so, PR is welcomed!
What is your proposal? I think generally in memory data structure (struct) is not always the same as persistent ones (database table). On the other hand, when performing dynamic query, we'd need some extra virtual columns (computed by expressions). Would you mind sharing a bit on what app you are building now?

**Comment by Follpvosten** [comment]
Having looked at this in more detail now, it actually also applies to my project that the in-memory model will almost never need to represent the whole database model, except for INSERTs. So I decided to just go for `#[derive(Iden)]` on your table enum for now.

I have an already working MVP (that's hardcoded to snake_case currently, but it's also fully customizable with variant attributes, so I could actually use this as-is in our project) here: https://git.karpador.xyz/Follpvosten/sea-query-derive

I've also realized that the easiest way to make this explicitly optional would be not integrating it into sea-query at all, but keeping it in a separate crate; this is required for proc-macros anyways, and sea-query might or might not provide a "derive" feature that just re-exports the "Iden" macro.

I can't share too much about my employer's project using sea-query, but I can say that it will also require many joins and computed properties, so I'm discarding the struct idea for now.

**Comment by billy1624** [comment]
Brilliant implementation!! Would you mind sharing the code to this Github repository? We can put both sea-query and sea-query-derive on the same workspace. Also, publishing the sea-query-derive as a separate crate.

**Comment by Follpvosten** [comment]
Of course I wouldn't! I just added support for Unit structs and container attributes (as in `#[iden = "tablename"] enum Thing { Table, ... }` and `#[derive(Iden)] #[iden = "uuid"] struct UuidType;` for one-off idens like for custom types). I've never set up a Cargo workspace before tho, so I'm not sure if I can just do that; maybe you can create the workspace and I can then add my code to it in a PR?

**Comment by Follpvosten** [comment]
Actually I could probably do it, now that I've looked into it, but I would have to move pretty much the whole content of the repo except for the README and licenses?

**Comment by tyt2y3** [comment]
Can you use the #8 branch for this operation?

**Comment by Follpvosten** [comment]
I've opened a PR into that branch.

**Comment by tyt2y3** [comment]
Thank you for your contribution! We will tweak a little bit and prepare a release. 
Since you are the author of `sea-query-derive`, do you want to be added as the crate owner too?

**Comment by Follpvosten** [comment]
Alright, great!
No, I'm already in the authors field of the sea-query-derive crate; that's enough for me for now. If I do become a regular contributor in the future, I'll reconsider it.

**Comment by tyt2y3** [comment]
#14
