### ISSUE TITLE
Document on_conflict usage

### ISSUE THREAD

**Issue by SebastienGllmt** [SeaQL/sea-query#302]
## Summary

support for `ON CONFLICT` was added in #279. However, nothing was added about this in the [insert documentation](https://www.sea-ql.org/SeaORM/docs/basic-crud/insert).

## Motivation

It would be good to document this functionality in the docs. Notably, it's not clear to me how I would use the `on_conflict` feature when inserting via a `ActiveModel `

**Comment by SebastienGllmt** [comment]
Turns out it's because the feature isn't included in sea-orm. You can find the PR that adds this feature here: https://github.com/SeaQL/sea-orm/pull/671

**Comment by billy1624** [comment]
Yes, it's currently in progress! Thanks!! @SebastienGllmt
