### ISSUE TITLE
Potential breaking changes from 0.23.0 to 0.24.0

### ISSUE THREAD

**Issue by phungleson** [SeaQL/sea-query#303]
## Description

Hey peeps, I encounter 2 errors when trying to upgrade from 0.23.0 to 0.24.0.

## Steps to Reproduce

First one, this used to work in 0.23.0

```
Query::insert()
        .into_table(Shops::Table)
        .columns(vec![
            ...
            Shops::GroupId,
            ...
        ])
        .exprs(vec![
            ...
            Expr::value(group_id.clone()),
```

With `group_id` is `&Option<Uuid>`

and

```
group_id UUID REFERENCES groups (id) ON DELETE CASCADE,
```

But it throws an error in 0.24.0

```
column \"group_id\" is of type uuid but expression is of type boolean
```

Second one, this used to work in 0.23.0

```
Query::insert()
        .into_table(Shops::Table)
        .columns(vec![
            ...
            Shops::Description,
            ...
        ])
        .exprs(vec![
            ...
            Expr::value(description.clone()),
```

With `description` is `&Option<String>`

and

```
description VARCHAR,
```

But it throws an error in 0.24.0

```
incorrect binary data format in bind parameter 4
```

### Expected Behavior

I downgraded back to 0.23.0 and they all working again.

### Actual Behavior

Provided.

### Reproduces How Often

Provided.

## Versions

Provided.

## Additional Information

I am testing with postgres, let me know if you need me to debug further.

Thanks!

**Comment by ikrivosheev** [comment]
@phungleson hello, thank you for the report, I will look this bug tomorrow...

**Comment by tyt2y3** [comment]
Yeah it seems to have caught by our CI now

**Comment by billy1624** [comment]
I guess the bug originate from the fact that we bind `Option<T>` as `Option::<bool>::None` if it's a `None`

- https://github.com/SeaQL/sea-query/blob/09a75b7de4cfd6a5ed4f2e01aaf469e686e29715/sea-query-driver/src/sqlx_mysql.rs#L71-L78
- https://github.com/SeaQL/sea-query/blob/09a75b7de4cfd6a5ed4f2e01aaf469e686e29715/sea-query-driver/src/sqlx_postgres.rs#L77-L84
- https://github.com/SeaQL/sea-query/blob/09a75b7de4cfd6a5ed4f2e01aaf469e686e29715/sea-query-driver/src/sqlx_sqlite.rs#L71-L78

**Comment by ikrivosheev** [comment]
@phungleson @tyt2y3 @billy1624 I apologize for the mistake. I did PR)

**Comment by Sytten** [comment]
My CI tests broke for 0.24 but I didnt have time to investigate, I will report back

**Comment by phungleson** [comment]
Thanks for quick turn around @ikrivosheev 👍

**Comment by tyt2y3** [comment]
Thank you @ikrivosheev 
A new release has been made [0.24.2](https://github.com/SeaQL/sea-query/releases/tag/0.24.2)
