### ISSUE TITLE
Remove deprecated methods

### ISSUE THREAD

**Issue by ikrivosheev** [SeaQL/sea-query#320]
## Summary

We have some deprecated functions:

- [ ] https://github.com/SeaQL/sea-query/blob/master/src/shim.rs#L72 **since = "0.12.0"**
- [ ] https://github.com/SeaQL/sea-query/blob/master/src/shim.rs#L98 **since = "0.9.0"**
- [ ] https://github.com/SeaQL/sea-query/blob/master/src/shim.rs#L126 **since = "0.9.0"**
- [ ] https://github.com/SeaQL/sea-query/blob/master/src/query/condition.rs#L410 **since = "0.12.0"**
- [ ] https://github.com/SeaQL/sea-query/blob/master//src/query/ordered.rs#L103 **since = "0.9.0"**
- [ ] https://github.com/SeaQL/sea-query/blob/master//src/query/ordered.rs#L154 **since = "0.9.0"**
- [ ] https://github.com/SeaQL/sea-query/blob/master//src/query/update.rs#L89 **since = "0.5.0"**
- [ ] https://github.com/SeaQL/sea-query/blob/master//src/query/select.rs#L461 **since = "0.9.0"**
- [ ] https://github.com/SeaQL/sea-query/blob/master//src/query/select.rs#L536 **since = "0.9.0"**
- [ ] https://github.com/SeaQL/sea-query/blob/master//src/query/select.rs#L590 **since = "0.6.1"**
- [ ] https://github.com/SeaQL/sea-query/blob/master//src/query/select.rs#L894 **since = "0.9.0"**
- [ ] https://github.com/SeaQL/sea-query/blob/master//src/query/select.rs#L965 **since = "0.6.1"**
- [ ] https://github.com/SeaQL/sea-query/blob/master//src/query/select.rs#L977 **since = "0.9.0"**
- [ ] https://github.com/SeaQL/sea-query/blob/master//src/query/select.rs#L1271 **since = "0.6.1"**
- [ ] https://github.com/SeaQL/sea-query/blob/master//src/query/select.rs#L1544 **since = "0.9.0"**
- [ ] https://github.com/SeaQL/sea-query/blob/master//src/query/select.rs#L1702 **since = "0.12.0"**
- [ ] https://github.com/SeaQL/sea-query/blob/master/src/foreign_key/create.rs#L119 **since = "0.10.2"**
- [ ] https://github.com/SeaQL/sea-query/blob/master/src/foreign_key/create.rs#L104 **since = "0.10.2**

## Releases:

1. [0.5.0](https://github.com/SeaQL/sea-query/releases/tag/0.5.0) Date: **Feb 09, 2021**
2. [0.6.1](https://github.com/SeaQL/sea-query/releases/tag/0.6.1) Date: **Mar 05, 2021**
3. [0.9.0](https://github.com/SeaQL/sea-query/releases/tag/0.9.0) Date: **Mar 29, 2021**
4. [0.10.2](https://github.com/SeaQL/sea-query/releases/tag/0.10.2) Date: **Apr 27, 2021**
5. [0.12.0](https://github.com/SeaQL/sea-query/releases/tag/0.12.0) Date: **May 31, 2021**

Perhaps we should remove them?

**Comment by tyt2y3** [comment]
Agree. They all seem old enough now :)
