### ISSUE TITLE
`sea-query` statements should qualify schema name

### ISSUE THREAD

**Issue by nahuakang** [SeaQL/sea-query#338]
## Motivation

Linked to [sea-orm issue 521](https://github.com/SeaQL/sea-orm/issues/521): `sea-orm-cli migrate` should respect the `DATABASE_SCHEMA` for Postgres in the specified in a project's `.env` file. This is currently not respected and the migration is done on the `public` schema.

## Proposed Solutions

Update all statement types in `sea-query` to quantify the schema name for Postgres. Check all `stmt` in the link below and see if any table reference is of `Iden` type, it should be changed to `TableRef`.

Also, some statement support schema scope, for example, type name could have schema prefix [e.g. in Postgres](https://www.postgresql.org/docs/current/sql-createtype.html). We can update it from `Iden` to `IdenList`.

https://github.com/SeaQL/sea-orm/blob/183639dc8c817fbd3211a87c67bcb983db4050ed/sea-orm-migration/src/manager.rs#L37-L89

## Additional Information

[See discussion here](https://github.com/SeaQL/sea-orm/issues/521)

**Comment by billy1624** [comment]
Hey @nahuakang, let me know if you need help :)
