### ISSUE TITLE
Version 0.25.0 not found

### ISSUE THREAD

**Issue by maxclaey** [SeaQL/sea-query#339]
## Description

When selecting version `"0.25.0"` for `sea-query`, cargo reports it failed to select a version, with the latest candidate version being `0.24.6`, even after updating the crates.io index. However, the latest version listed on [crates.io](https://crates.io/crates/sea-query) is 0.25.0. Reproduced on an ubuntu and macos setup. Removing `~/.cargo/registry` doesn't help.

## Steps to Reproduce

1. Update sea-query dependency version to `"0.25.0"`
2. Run e.g. `cargo check`

### Expected Behavior

The correct version is found

### Actual Behavior

Cannot select a version:
```
    Updating crates.io index
error: failed to select a version for the requirement `sea-query = "^0.25.0"`
candidate versions found which didn't match: 0.24.6, 0.24.5, 0.24.4, ...
location searched: crates.io index
```

### Reproduces How Often

Reproduced on a macos and ubuntu setup.

## Versions

0.25.0

## Additional Information

```
cargo 1.58.0 (f01b232bc 2022-01-19)
rustc 1.58.1 (db9d1b20b 2022-01-20)
```

**Comment by billy1624** [comment]
Hey @maxclaey, thanks for the report! Could you please run and show me the output of `cargo tree | grep sea-`?

**Comment by billy1624** [comment]
Btw... I wonder if `cargo update` solve the issue?

**Comment by maxclaey** [comment]
@billy1624 Thanks for your response! Running `cargo update` gives the same response:
```
    Updating crates.io index
error: failed to select a version for the requirement `sea-query = "^0.25.0"`
candidate versions found which didn't match: 0.24.6, 0.24.5, 0.24.4, ...
location searched: crates.io index
```
The same holds for `cargo tree | grep sea-`. In the meanwhile I figured out that it works when using rustc 1.60.0 or above (rustc 1.59.0 still has the same issue). Is there a minimum rustc version that is required for the latest version of sea-query?

**Comment by maxclaey** [comment]
Agreed, it would be nice to at least sea this requirement :)! Thanks for clarifying!

**Comment by billy1624** [comment]
I'm going to transfer this issue to `sea-query`

**Comment by billy1624** [comment]
Oppps... this issue is on `sea-query`. Ignore me plz loll
