### ISSUE TITLE
Use IntoIterator in public api functions

### ISSUE THREAD

**Issue by Progdrasil** [SeaQL/sea-query#34]
In order to be more [idiomatic](https://rust-lang.github.io/api-guidelines/flexibility.html?highlight=IntoIterator#functions-minimize-assumptions-about-parameters-by-using-generics-c-generic) the use of generics would be preferable to asking for `Vec` as parameters.

Take for example SelectStatement::columns which has a signature as follows:
```rust
pub fn columns<T>(&mut self, cols: Vec<T>) -> &mut Self
    where T: IntoColumnRef
```
This could become
```rust
pub fn columns<T, I>(&mut self, cols: I) -> &mut Self
    where
        T: IntoColumnRef,
        I: IntoIterator<Item = T>
```

This stems from the discussion in #15.

**Comment by duchainer** [comment]
Started https://github.com/duchainer/sea-query/tree/more-generic-into-iterator-instead-of-vec

**Comment by tyt2y3** [comment]
Thanks! Let me know when you think it's ready.

**Comment by tyt2y3** [comment]
Thank you so much of the big effort!
