### ISSUE TITLE
Table Column with Default Expression

### ISSUE THREAD

**Issue by billy1624** [SeaQL/sea-query#347]
## Motivation
- Currently, we support column with default value but not default expression
- Having default expression in column such as timestamp / datetime is very common, e.g. `CURRENT_TIMESTAMP` as the default expression

## Proposed Solutions
- `ColumnSpec::Default(Value)` should be changed to holding `SimpleExpr`, i.e. `ColumnSpec::Default(SimpleExpr)`
  https://github.com/SeaQL/sea-query/blob/6c9527ae08e32c55490ae510be41f646e030c2a2/src/table/column.rs#L48-L58
- Keep the old `default` method and introduce a new method called `default_expr` which take any `Into<SimpleExpr>`
  https://github.com/SeaQL/sea-query/blob/6c9527ae08e32c55490ae510be41f646e030c2a2/src/table/column.rs#L142-L149

**Comment by ikrivosheev** [comment]
@billy1624, hello! I will do this.

**Comment by billy1624** [comment]
Thanks! @ikrivosheev

**Comment by billy1624** [comment]
Related Discussion:
- https://github.com/SeaQL/sea-query/discussions/346

**Comment by ikrivosheev** [comment]
@billy1624 what do you think about new `Enum` for table? We only need two variants from `SimpleExpr`

1. FuncionCall
2. Value
3. Custom

**Comment by ikrivosheev** [comment]
No, bad ideas... We need to split QueryBuilder. For unavailable operations panic.

**Comment by billy1624** [comment]
Hey @ikrivosheev, sorry for the delay. 

> @billy1624 what do you think about new `Enum` for table? We only need some variants from `SimpleExpr`

Do you mean introducing a new `Enum` for the "Default Value" of a column? https://github.com/SeaQL/sea-query/blob/63e18941fad55e391e4abb1316fd81e7a7768f91/src/table/column.rs#L51-L61

```
pub enum ColumnSpec {
...
    Default(DefaultValue)
...
}

// I just makeup the name, feel free to rename it :)
pub enum DefaultValue {
    Func(Function),
    Value(Value),
    Custom(String),
}
```

Something like this?

**Comment by tyt2y3** [comment]
1. I think we should rename the old `default` to `default_value` and the new `default` is an alias of `default_expr`
2. Yes I think having a dedicated `DefaultColumnExpr` is a good idea

**Comment by ikrivosheev** [comment]
@tyt2y3 @billy1624 hello! I have made several attempts and understand that is better to use `SimpleExpr` instead create `DefaultColumnExpr`

**Comment by tyt2y3** [comment]
I have no objection to either

**Comment by billy1624** [comment]
Hello @ikrivosheev, are you working on this?
