### ISSUE TITLE
Support VALUES lists in select queries

### ISSUE THREAD

**Issue by samtay** [SeaQL/sea-query#350]
## Motivation

I'd like to be able to make constant tables from in-memory values via [VALUES lists](https://www.postgresql.org/docs/current/queries-values.html). For example a CTE like

```sql
with groups_cte(id, name) as (
  select * from (values (1, 'hello'), (2, 'world'))
)
select * from users inner join groups_cte on users.group_id = groups_cte.id
```

## Proposed Solutions

Currently [`SelectStatement::from`](https://docs.rs/sea-query/0.25.0/sea_query/query/struct.SelectStatement.html#method.from) accepts an `IntoTableRef`. Given that Postgres itself refers to such lists as constant tables, it could be reasonable to just add the variant `TableRef::Values(Vec<ValueTuple>)` and an impl
```rust
impl<I, V> IntoTableRef for I
where
    I: IntoIterator<Item = V>,
    V: IntoValueTuple,
{}
```
However I'm unaware of other databases support for this; after a very brief search, it looks like MySQL has some variant of this, and SQLite does not. It could perhaps just be implemented a Postgres or Postgres/MySQL specific option.

## Additional Information

Note that VALUES lists are supported on `insert` and `update` currently, just not on `select`. However, those places only allow a single row e.g. `values: Vec<Value>`, and for this to be more useful in select queries, it should really be an iterator of iterators `values: Vec<Vec<Value>>` with some way to enforce the same size inner iterators. I've suggested an iterator of [`ValueTuple`](https://docs.rs/sea-query/0.25.0/sea_query/value/enum.ValueTuple.html)s above, but that type should probably have more instances for larger tuples. A bit of a separate issue, but it might be nice to use the same approach for the `insert`/`update` values, to allow a multi-insert.

**Comment by samtay** [comment]
I tried to hack my way to a temporary solution using `unnest`, but to unnest to multiple columns the unnest needs to happen in the FROM clause i.e. `SELECT * FROM unnest(array[...])`, which gets back to the original issue. If you `SELECT unnest(array[...])` the best you can get is a single column tuple in the result set, which doesn't work for my case of wanting to be able to join on columns from the CTE.

I would think that, since sea-query is still very much in development and can't offer every piece of SQL functionality, perhaps escape hatches should be offered in these important places? Similar to the `Expr::cust_with_values` that accepts strings, have a way to `Query::select().from(From::cust_with_values("unnest(array[...])", vec![...]))`?

**Comment by billy1624** [comment]
Hey @samtay, I guess we can get a consensus on how to construct such "constant tuple list" in SQL. before we decide how to implement one in SeaQuery.

> REF: https://www.postgresql.org/docs/current/queries-values.html

This `VALUES ( ... )` syntax wasn't supported in all databases.

```sql
VALUES (1, 'one'), (2, 'two'), (3, 'three');
```

Alternatively, we can rewrite it into... and it works on all databases.
- MySQL: https://dbfiddle.uk/?rdbms=mysql_8.0&fiddle=b83d8ac0a48ad1a81d75476f0071365d
- MariaDB: https://dbfiddle.uk/?rdbms=mariadb_10.6&fiddle=b83d8ac0a48ad1a81d75476f0071365d
- SQLite: https://dbfiddle.uk/?rdbms=sqlite_3.27&fiddle=b83d8ac0a48ad1a81d75476f0071365d
- PostgreSQL: https://dbfiddle.uk/?rdbms=postgres_14&fiddle=b83d8ac0a48ad1a81d75476f0071365d

```sql
SELECT tbl.*
FROM (SELECT 1     AS column1,
             'one' AS column2
      UNION
          ALL
      SELECT 2,
             'two'
      UNION
          ALL
      SELECT 3,
             'three') AS tbl
WHERE tbl.column1 >= 2;
```

---

Btw... out of curiosity. Is there any reason you need to also include the `name` column in the list? Isn't that sufficient to include the `id` column in the select statement?

> ```sql
> with groups_cte(id, name) as (
>   select * from (values (1, 'hello'), (2, 'world'))
> )
> select * from users inner join groups_cte on users.group_id = groups_cte.id
> ```

For example,

```
select * from users inner join groups_cte on users.group_id IN (1, 2)
```

**Comment by samtay** [comment]
Generating all those unions does _work_ but, it seems a tad smelly; I'd want to inspect the query planner or do some testing and make sure that it's not too inefficient for large lists.

> Btw... out of curiosity. Is there any reason you need to also include the name column in the list? Isn't that sufficient to include the id column in the select statement?

Your suggestion works for simple cases, yes. But imagine the outer query needs to sort by the group name, and deliver paginated results, i.e. the get the first 10 users sorted by group name where there might be 10^n such users in the table.
