### ISSUE TITLE
[Feature Request] Add cross join

### ISSUE THREAD

**Issue by negezor** [SeaQL/sea-query#373]
## Motivation

https://en.wikipedia.org/wiki/Join_(SQL)#Cross_join

## Proposed Solutions

```rs
.join(JoinType::CrossJoin, tbl_ref, condition)

.join_lateral(JoinType::CrossJoin, query, alias, condition)
```

## Additional Information

It often helps to be more explicit about your intentions.

**Comment by ikrivosheev** [comment]
@negezor hello! Thank you for Proposal. I created PR.
