### ISSUE TITLE
Support Table `CHECK` Constraints

### ISSUE THREAD

**Issue by billy1624** [SeaQL/sea-query#397]
### Discussed in https://github.com/SeaQL/sea-query/discussions/135

<div type='discussions-op-text'>

<sup>Originally posted by **forrest-akin** August  3, 2021</sup>
Currently, there's no way to specify table `CHECK` constraints in [`TableCreateStatement`](https://docs.rs/sea-query/0.12.8/sea_query/table/struct.TableCreateStatement.html#)s. Adding an `.extra()` method similar to [`ColumnDef`](https://docs.rs/sea-query/0.12.8/sea_query/table/struct.ColumnDef.html#method.extra) would probably be the easiest way to add support for this.</div>

**Comment by billy1624** [comment]
After some digging I found all three databases support CHECK constraint:
- SQLite: https://www.sqlite.org/lang_createtable.html#check_constraints
- MySQL: https://dev.mysql.com/doc/refman/8.0/en/create-table-check-constraints.html
- PostgreSQL: https://www.postgresql.org/docs/current/ddl-constraints.html

**Comment by billy1624** [comment]
I'll open this issue for contributions

**Comment by ikrivosheev** [comment]
> wave Hey @billy1624! Happy to claim this if it's okay with you!

Done!

**Comment by Razican** [comment]
@nahuakang is there any news with this?

**Comment by nahuakang** [comment]
@Razican Sorry I haven't had the time to got around to this issue. Are you interested in taking it? If so, please do :) I probably will only come back to this in 2-3 weeks earliest.

**Comment by LemarAb** [comment]
Id be happy to give it a go :)

**Comment by ikrivosheev** [comment]
@LemarAb hello! Any updates?)

**Comment by LemarAb** [comment]
> 

@ikrivosheev I made some progress but need some time to deeper understand how sea query translates the stmt into SQL. Will report soon. If necessary, can I ask you for help?

**Comment by ikrivosheev** [comment]
> > 
> 
> @ikrivosheev I made some progress but need some time to deeper understand how sea query translates the stmt into SQL. Will report soon. If necessary, can I ask you for help?

Take your time! Yes, of course you can)

**Comment by LemarAb** [comment]
Just to clarify: CHECK constraints on Columns are already supported trough the extra() method. We want to add CHECK constraints for the whole table, right? As an example for Postgres: 

```
CREATE TABLE products (
    product_no integer CHECK(product_no >0),
    name text,
    CONSTRAINT valid_discount CHECK (price > discounted_price)
);
```
We want to add support for the second constraint, the first is already supported, correct?

@ikrivosheev

**Comment by ikrivosheev** [comment]
@LemarAb we want to add the ability to add `CHECK` constraint using SeaQuery, without `extra` method.

**Comment by LemarAb** [comment]
@ikrivosheev ok, so afaik we need to add check() to '''ColumnDef''' and to '''TableCreateStatement''' ?
