### ISSUE TITLE
Add ability to select from function

### ISSUE THREAD

**Issue by DDtKey** [SeaQL/sea-query#398]
## Motivation

It's actually possible to `select` from function, at least this is fair for postgres (e.g: `select * from custom_function()`)
Moreover, [AWS Aurora](https://aws.amazon.com/rds/aurora/) uses this approach (e.g:  [aurora_replica_status() doc](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora_replica_status.html))

## Proposed Solutions

I think the maintainers know the best way to do this. 
But perhaps it's possible to implement `IntoTableRef` for `Func`.  
So the following code will work:  
```rs
Query::select().from(Func::cust("my_func"))
```

In this approach, probably, make sense to rename trait `IntoTableRef`

**Comment by tyt2y3** [comment]
I think we have had `TableRef::SubQuery` i.e. `from_subquery` so that you can actually `SELECT * from (SELECT custom_function())`

Syntactically they are different, but I think they are the same thing.

**Comment by DDtKey** [comment]
It looks like workaround 🤔

And probably can degrade the query execution plan

**Comment by ikrivosheev** [comment]
@DDtKey @tyt2y3 hello! I create PR.
