### ISSUE TITLE
[SeaQuery] Support `time` crate on SQLite

### ISSUE THREAD

**Issue by billy1624** [SeaQL/sea-query#409]
Native support of `time` crate has been added in PR https://github.com/launchbadge/sqlx/pull/1865 and released as part of SQLx [0.6.1](https://github.com/launchbadge/sqlx/blob/main/CHANGELOG.md).

Now we could bind `time` on to SQLite query statement and get `time` from SQLite directly.

**Comment by kyoto7250** [comment]
I want to try it.

Do we need to rewrite around these codes? 

https://github.com/SeaQL/sea-query/blob/e9f961eb760d81f80817aae61f502eba409846dd/sea-query-binder/src/sqlx_sqlite.rs#L76-L90

**Comment by kyoto7250** [comment]
@ikrivosheev 
Thank you, I will try it :)

**Comment by ikrivosheev** [comment]
> @ikrivosheev Thank you, I will try it :)

It doesn't look very hard) Good look, ping me if you need help
