### ISSUE TITLE
Adding `filter`s after adding a `Condition::any` in another call results in `OR` instead of `AND`

### ISSUE THREAD

**Issue by e-rhodes** [SeaQL/sea-query#414]
## Description
When querying data, adding a filter using a `Condition::any` causes any further calls to `filter` to also be part of that `any` condition.

## Steps to Reproduce

1. Create a query with a filter using a `Condition::any`
2. Add another condition in a separate call to `filter`

### Expected Behavior
I'd expect this:
```rust
Entity::find()
        .filter(
            Condition::any()
                .add(Column::Field2.eq("dog"))
                .add(Column::Field3.eq("dog")),
        )
        .filter(Column::Field1.eq(1))
```
to be equivalent to this:
```rust
Entity::find()
        .filter(Column::Field1.eq(1))
        .filter(
            Condition::any()
                .add(Column::Field2.eq("dog"))
                .add(Column::Field3.eq("dog")),
        )
```

### Actual Behavior

The first produces:
```sql
SELECT `table`.`field1`, `table`.`field2`, `table`.`field3` FROM `table` WHERE `table`.`field2` = 'dog' OR `table`.`field3` = 'dog' OR `table`.`field1` = 1
```
While the second produces the expected output of:
```sql
SELECT `table`.`field1`, `table`.`field2`, `table`.`field3` FROM `table` WHERE `table`.`field1` = 1 AND (`table`.`field2` = 'dog' OR `table`.`field3` = 'dog')
```

### Reproduces How Often
Every time

## Versions
```
sea-orm v0.9.1
    ├── sea-orm-macros v0.9.1 (proc-macro)
    ├── sea-query v0.26.2
    │   ├── sea-query-derive v0.2.0 (proc-macro)
    │   ├── sea-query-driver v0.2.0 (proc-macro)
    ├── sea-strum v0.23.0
    │   └── sea-strum_macros v0.23.0 (proc-macro)
```

Ubuntu 22.04 on WSL in Windows 11

## Additional Information

<https://github.com/e-rhodes/sea-orm-filter-and-or>

**Comment by tyt2y3** [comment]
An anecdote: there was only `and_where` in the first place. Then `Condition` was introduced, which was meant to be *the only* condition tree, calling `cond_where` a 2nd time would replace the current where clause. This is not consistent with the behaviour of the rest of the API, so I extended it to conjoining conditions together, and probably overlooked the sequential behaviour.

**Comment by Sytten** [comment]
The work around I have been using for a while now is to always put a `.cond_where(Condition::all())` before any filter. That solves the issue.

**Comment by tyt2y3** [comment]
> The work around I have been using for a while now is to always put a `.cond_where(Condition::all())` before any filter. That solves the issue.

Ah, I did not intended / aware this strangeness. At least we changed this now
