### ISSUE TITLE
`INTERSECT` operator for select statements

### ISSUE THREAD

**Issue by liningpan** [SeaQL/sea-query#427]
## Motivation

I'm searching through the documentation. There seems to be no support for `INTERSECT` operators. I found that the `UNION` operator is supported. Is there a reason for not supporting `INTERSECT`? Would you accept PR?

**Comment by billy1624** [comment]
Hey @liningpan, welcome!! A PR would be appreciated :D

Some directions: start by adding a new variant `INTERSECT` (we may well add `EXCEPT` as well) to `UnionType`
- https://github.com/SeaQL/sea-query/blob/cb6fd12ecec848cfe90f05ad7f2a27f2db25028c/src/query/select.rs#L118-L123

Then, compile it, Rust compiler will tell you what's missing and what you have to change.

Feel free to ping me if you need help along the way.
