### ISSUE TITLE
Remove `CURRENT_TIMESTAMP` from function

### ISSUE THREAD

**Issue by tyt2y3** [SeaQL/sea-query#440]
We should remove `CURRENT_TIMESTAMP` from function and put it under SystemVariable (or SysVar) instead.

_Originally posted by @tyt2y3 in https://github.com/SeaQL/sea-query/issues/349#issuecomment-1246374594_

**Comment by billy1624** [comment]
Yeah, that make more sense. Basically, `CURRENT_TIMESTAMP` is a system variable (or constant) and `CURRENT_TIMESTAMP()` is a function.

**Comment by billy1624** [comment]
Context: https://github.com/SeaQL/sea-query/commit/70c25784730b7d220e6878804badf1c72e255d43#commitcomment-83866265

> Hey @tyt2y3, I don't think this is correct for SQLite and PostgreSQL.
> 
> Both of them expect `CURRENT_TIMESTAMP` instead of `CURRENT_TIMESTAMP()`.
> 
> * https://www.sqlite.org/lang_keywords.html
> * https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-CURRENT
> 
> You can write a select query `SELECT CURRENT_TIMESTAMP;` [here](https://dbfiddle.uk/) to test it.

**Comment by ikrivosheev** [comment]
@tyt2y3 @billy1624 i create PR which fix this
