### ISSUE TITLE
Alter `TableRef` for Any Statement Type That Implements a (New) Trait

### ISSUE THREAD

**Issue by nahuakang** [SeaQL/sea-query#445]
## Motivation

Issue for self-assignment and tracking :)

Following [this discussion](https://github.com/SeaQL/sea-orm/pull/981#issuecomment-1236691534), we need to implement a trait that allows the access and modification of `TableRef` on all statement types that implement the said trait to continue working on [sea-orm #981](https://github.com/SeaQL/sea-orm/pull/981). The statement types that should implement this trait includes:

- TableCreateStatement
- TableAlterStatement
- TableDropStatement
- TableRenameStatement
- TableTruncateStatement
- IndexCreateStatement
- IndexDropStatement
- ForeignKeyCreateStatement
- ForeignKeyDropStatement
- TypeCreateStatement
- TypeAlterStatement
- TypeDropStatement

## Proposed Solutions

The trait:

```rust
pub trait SchemaDefinitionStatement {
    fn get_table_name(&self) -> Option<&TableRef>;

    fn set_table_name(&self) -> &mut Self;

    fn prefix_table_name_with_schema<A>(&mut self, schema: A) -> &mut Self
    where
        A: IntoIden + 'static;
}
```

Helper on `TableRef`:

```rust
impl TableRef {
    pub fn schema<A>(self, schema: A) -> Self
    where
        A: IntoIden + 'static,
    {
        match self {
            ...
        }
    }
}
```

**Comment by nahuakang** [comment]
@billy1624 I might try just add 1 method to `SchemaDefinitionStatement` since the type-related statements have `TypeRef` instead of `TableRef` and some statements have `Vec<TableRef>` instead of `Option<TableRef>`:

```rust
pub trait SchemaDefinitionStatement {
    fn prefix_table_name_with_schema<A>(&mut self, schema: A) -> &mut Self
    where
        A: IntoIden + 'static;
}
```

Let me know if you think it's a bad idea :)

**Comment by billy1624** [comment]
> @billy1624 I might try just add 1 method to `SchemaDefinitionStatement` since the type-related statements have `TypeRef` instead of `TableRef` and some statements have `Vec<TableRef>` instead of `Option<TableRef>`:

This make sense to me :P

But we might want to rename the trait then. Let me think...
Thoughts? @nahuakang @ikrivosheev @tyt2y3

**Comment by ikrivosheev** [comment]
@nahuakang maybe add associated type to trait? For with: `TypeRef`, `TableRef`?

**Comment by nahuakang** [comment]
@billy1624  also made [this PR](https://github.com/SeaQL/sea-orm/pull/1056), which might resolve this issue?

**Comment by billy1624** [comment]
Hey @nahuakang, you're correct! This feature is no longer needed. This is part of https://github.com/SeaQL/sea-orm/issues/521 but we don't need it now as we figure out another way to achieve it.

**Comment by billy1624** [comment]
I'll close this now. In case anyone interested on this. Please leave a comment and consider reopen this :)
