### ISSUE TITLE
`distinct_on` doesn't work when specifying a table in addition to a column

### ISSUE THREAD

**Issue by Cobular** [SeaQL/sea-query#449]
## Description

The `distinct_on` clause doesn't work with a tuple column def
## Steps to Reproduce

Run the following code

### Expected Behavior

```rust
let test2 = Query::select()
    .from(files::Entity)
    .distinct_on(vec![files::Column::Id])
    .columns(vec![(files::Entity, files::Column::Id)])
    .to_owned();

let thing2 = test2.build(PostgresQueryBuilder);
println!("{:?}", thing2.0);
``` 
returns the following: 
```sql
SELECT DISTINCT ON (\"id\") \"files\".\"id\" FROM \"files\"
```

### Actual Behavior

**If we ask for it to be distinct on a ColumnDef with a table specifier (or anything else beyond just a column)**
```
let test2 = Query::select()
    .from(files::Entity)
    .distinct_on(**vec![(files::Entity, files::Column::Id)]**)
    .columns(vec![(files::Entity, files::Column::Id)])
    .to_owned();
```

**we don't get the distinct on:**
```sql
SELECT \"files\".\"id\" FROM \"files\"
```

### Reproduces How Often

Every time

## Versions

0.26.3

**Comment by Cobular** [comment]
ColumnRef: https://github.com/SeaQL/sea-query/blob/a7f2defac169c93f9b6a059264d9ba52aebb9b43/src/types.rs#L61-L68

SelectDistinct: https://github.com/SeaQL/sea-query/blob/a7f2defac169c93f9b6a059264d9ba52aebb9b43/src/query/select.rs#L59-L65


Basically, `SelectDistinct` takes a vec of `DynIden`, however the `ColumnRef` that we pass into `distinct_on()` is only compatible with `DynIden` in one of it's cases. This means that if you provide any other case of `ColumnRef`, the call to `distinct_on()` fails silently.

**Comment by Cobular** [comment]
As mentioned on discord by Billy:

> Instead, we should have store ColumnRef directly, i.e. `SelectDistinct::DistinctOn(Vec<ColumnRef>)`.

This introduces a new problem when it comes to stringily the `ColumnRef`:

https://github.com/SeaQL/sea-query/blob/a7f2defac169c93f9b6a059264d9ba52aebb9b43/src/backend/postgres/query.rs#L19-L36

The current stringily implementation doesn't work here, we can't call `c.prepare()` if `c` is just a `ColumnRef`. I'm not sure what the best approach would be - maybe impl something new on `ColumnRef` or just write a function that works here? 

(I feel like this impl to stringily a ColumnRef must exist somewhere given it happens all over. Guidance on what that would be called would be great!

**Comment by Cobular** [comment]
Edit: It looks like we need `prepare_column_ref()`

**Comment by billy1624** [comment]
Yep! That's the easiest and the correct way hahaa
