### ISSUE TITLE
Replace `and_where` and `or_where` with `any` and `all`

### ISSUE THREAD

**Issue by nitnelave** [SeaQL/sea-query#45]
Currently, the way to write conditions is too close to SQL, yet different. To express `WHERE a AND b`, there are two possibilities:
`.and_where(a).and_where(b)` or `.or_where(a).and_where(b)`.

When we add more operations, things get messy:
`.and_where(a).or_where(b).and_where(c)` actually resolves differently depending on whether it's on a Select or a Delete/Update.

- In a Select, it will resolve to `WHERE a OR (b AND c)` due to the higher precedence of `AND` vs `OR`.
- In a Delete/Update, it will resolve to `WHERE (a OR b) AND c` because of enforced left-associativity.

In both cases, the semantics are not clear. Instead of `AND` and `OR`, the syntax should be based on `any` and `all`, and then resolved by the builder with the correct semantics. Something along these lines:

```rust
Query::delete()
  .from(Char::Table)
  .where(
    condition::any()
    .add(a)
    .add(
      condition::all()
      .add(b)
      .add(c)))
```

This would resolve to:
```sql
DELETE FROM char WHERE a OR (b AND c);
```

We can also add the macros `any!` and `all!` to get:
```rust
  .where(any![a, all![b, c]])
```

Regarding implementation, the existing `and_where` can be marked deprecated, and implemented as an `Either` with the any/all implementation, with a panic if both are used. Then with a major version bump we can remove the `and_where`.

WDYT?

**Comment by tyt2y3** [comment]
I totally support adding a generic `where` method accepting an expression tree as parameter.
Regarding the naming, why not simply name them as `logical::and()` and `logical::or()`, this is more intuitive I guess?
But I don't think it is needed to deprecate `and_where`, as they make the resulting code more readable.
May be we can simply deprecate `or_where` and warn people against mixing `and_where` and `or_where`.

**Comment by nitnelave** [comment]
There is precedent for the `any`/`all` with iterators: https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.any
In my mind, `or` makes more sense for inline operations, but `any`/`all` are better (and more common) for tree-style conditions like this.

+1 to keeping the `and_where` and deprecating the `or_where`. We'd still have to make it incompatible with the generic `where` though.
