### ISSUE TITLE
Deprecate `values` method in favour of `exprs` method

### ISSUE THREAD

**Issue by billy1624** [SeaQL/sea-query#451]
## Motivation

Since we have a blanket `From` implementation for any `Into<Value>` into `SimpleExpr`. We can now deprecate `values` method and use `exprs` method instead.

https://github.com/SeaQL/sea-query/blob/a7f2defac169c93f9b6a059264d9ba52aebb9b43/src/expr.rs#L2343-L2350

## Proposed Solutions

I think we can depredate
- [`TypeCreateStatement::values()`](https://docs.rs/sea-query/0.26.3/sea_query/extension/postgres/struct.TypeCreateStatement.html#method.values).

While keeping these two methods. The semantic is more natural to me. e.g. `insert values` and `update values`
- [`InsertStatement::values()`](https://docs.rs/sea-query/0.26.3/sea_query/query/struct.InsertStatement.html#method.values)
- [`UpdateStatement::values()`](https://docs.rs/sea-query/0.26.3/sea_query/query/struct.UpdateStatement.html#method.values)

**Comment by ikrivosheev** [comment]
@billy1624 hello!

- [`TypeCreateStatement::values()`](https://docs.rs/sea-query/0.26.3/sea_query/extension/postgres/struct.TypeCreateStatement.html#method.values) - cannot deprecate, because:
```rust
pub fn <T, I>(&mut self, values: I) -> &mut Self 
where
    T: IntoIden // <- IntoIden, not Into<Value>
    I: IntoIterator<Item = T>,
```

With other two methods I will try do this)

**Comment by ikrivosheev** [comment]
@billy1624 hello! I create PR, can you review it?)
