### ISSUE TITLE
Panic when building a query with chained `or`

### ISSUE THREAD

**Issue by nitnelave** [SeaQL/sea-query#453]
## Description

When creating a query with chained `.or(...)` statements, there's an `unwrap` on a `None`.
Tested with sea-query 0.25.2, it happens at `src/backend/query_builder.rs:1545`.

## Steps to Reproduce

Minimal reproducible unit test:

```rust
Query::select()
            .from(Users::Table)
            .cond_where(Expr::value(true).and(
            Expr::value(true)
                .or(Expr::value(true))
                .or(Expr::value(true)),
        )).build(SqliteQueryBuilder{});
```

## Versions

sea-query 0.25.2

**Comment by nitnelave** [comment]
I understand that it might not be the best way to use the API, and actually using `Cond::any()` would be a better way (and I updated my code for that), but it's a very less-than-ideal situation right now. Proposed solutions:
 - Change the `unwrap` to an `expect` that explains that you misused the API
 - Silently change the expression to a `Cond::any` to make it work anyway.

**Comment by tyt2y3** [comment]
Thanks for the suggestion. Documenting all unwraps and possible panics is definitely a thing we should do.

Btw, I changed the semantics of cond_where in the upcoming 0.27, would that also affect you?

**Comment by nitnelave** [comment]
How did the semantics change?

Right now I don't have a strong incentive to upgrade, so it won't affect me directly, but it might be nice to have some notes (changelog?) of incompatibilities between versions when upgrading.

**Comment by nitnelave** [comment]
Perfect :) Makes sense! That works for me.

**Comment by ikrivosheev** [comment]
@nitnelave can we close issue?

**Comment by nitnelave** [comment]
Yes!
