### ISSUE TITLE
Postgres bytea converted to bit

### ISSUE THREAD

**Issue by RichardOverzee** [SeaQL/sea-query#458]
## Description

While using sea_query version 0.26.3. When inserting a VecU8 into a postgres BYTEA column it is actually converted into a bit which cause the actual insert statement for a BYTEA to be prefixed by x'. Which is not what we want. 
Currently the work around is to parse it as a string so it can be inserted.

## Steps to Reproduce

1. 
Install  sea_query version 0.26.3
2. 
Create a postgres table with a BYTEA column type
3. 
Try insert a VecU8 such as
`let sql = Query:insert()
        .into_table((Alias::new(mySchema), MyEnumTable::Table))
        .columns([
            MyEnumTable::MyBYTEA,
        ])
        .values(vec![
            myVecU8.into(),
        ])?
        .to_string(PostgresQueryBuilder);
`

### Expected Behavior

I was expecting to insert a BYTEA into postgres and not a Bit

### Actual Behavior

Sea_query converted my bytes into a bit by prefixing the query with a 'x'

### Reproduces How Often

Always

## Versions

│   │   │   ├── sea-query v0.26.3
│   │   │   │   ├── sea-query-derive v0.2.0 (proc-macro)
│   │   │   │   ├── sea-query-driver v0.2.2 (proc-macro)
│   │   ├── sea-query v0.26.3 (*)
│   ├── sea-query v0.26.3 (*)
│   ├── sea-query v0.26.3 (*)
│   ├── sea-query v0.26.3 (*)

**Comment by billy1624** [comment]
Hey @RichardOverzee, thanks for catching this! I'll draft a PR to fix this in a bit.

**Comment by RichardOverzee** [comment]
@tyt2y3 the behavior is well explained by billy1624 here: https://github.com/SeaQL/sea-query/pull/459#issuecomment-1271251488
Is it a bug per say? I would say so. 
Postgres Bit type only accept 0's and 1's.
Postgres Bytea type support Hex values and the 'escape' format from postgres.
Rust Vec<u8> is more than juste 0's and 1's.
Why should a Vec<u8> (which can have other values than 0 or 1) be inserted into a postgres Bit type which only accept 0 or 1?.

**Comment by tyt2y3** [comment]
Then what's the correct syntax to encode a byte array indeed?

**Comment by ikrivosheev** [comment]
@tyt2y3 @billy1624 @RichardOverzee any updates? Or I can close issue?

**Comment by tyt2y3** [comment]
https://github.com/SeaQL/sea-query/pull/459#issuecomment-1305723796

**Comment by jmdeschenes** [comment]
As noted in the issue above by @tyt2y3, the proper fix is to make the encoding dependent on the Database:

## Current supported Databases

### Postgres

REF: https://www.postgresql.org/docs/current/datatype-binary.html

> The “hex” format encodes binary data as 2 hexadecimal digits per byte, most significant nibble first. The entire string is preceded by the sequence \x (to distinguish it from the escape format). In some contexts, the initial backslash may need to be escaped by doubling it (see [Section 4.1.2.1](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS)). For input, the hexadecimal digits can be either upper or lower case, and whitespace is permitted between digit pairs (but not within a digit pair nor in the starting \x sequence). The hex format is compatible with a wide range of external applications and protocols, and it tends to be faster to convert than the escape format, so its use is preferred

### SQLITE

REF: https://www.sqlite.org/lang_expr.html

> BLOB literals are string literals containing hexadecimal data and preceded by a single "x" or "X" character. Example: X'53514C697465'

### MySql

REF: https://dev.mysql.com/doc/refman/5.6/en/hexadecimal-literals.html

> Hexadecimal literal values are written using X'val' or 0xval notation, where val contains hexadecimal digits (0..9, A..F). Lettercase of the digits and of any leading X does not matter. A leading 0x is case-sensitive and cannot be written as 0X.

## Other Databases

### MSSQL
REF: https://learn.microsoft.com/en-us/sql/t-sql/data-types/constants-transact-sql?redirectedfrom=MSDN&view=sql-server-ver16#binary-constants

> Binary constants have the prefix 0x and are a string of hexadecimal numbers. They are not enclosed in quotation marks.
Here is a very good resume of the situation for most databases:

https://stackoverflow.com/questions/9320200/inline-blob-binary-data-types-in-sql-jdbc

**Comment by wikiwong** [comment]
I created a PR that addresses this issue: https://github.com/SeaQL/sea-query/pull/666

**Comment by ikrivosheev** [comment]
> I created a PR that addresses this issue: #666

@wikiwong hello! Thank you! I'm going to review it)

**Comment by wikiwong** [comment]
Thank you!
