### ISSUE TITLE
Add support for checking whether tables/columns exist

### ISSUE THREAD

**Issue by nitnelave** [SeaQL/sea-query#474]
## Motivation

In some somewhat manually-defined migration processes, it makes sense to check whether a given table or column exists. However, it's hard to do that in a portable way. AFAIK, Postgres/MySQL/MsSql have `information_schema.tables`, but SQlite has `sqlite_master`. I think it would be a good addition to sea-query to be able to support:
 - Check if table exists, list the columns
 - Check if column exists, give the type (?)

## Proposed Solutions

A first draft would be to add 2 new types of queries, `TableMetadata` and `ColumnMetadata`. Something like:

```rust
assert_eq!(
  Query::table_metadata(Users::Table)
    .order_by(sea_query::metadata::column::Name)
    .to_string(SqliteQueryBuilder), 
  r#(SELECT name from pragma_table_info(('users')) order by name;)#
);
```

Or we could "just" (if all engines support it) offer a reference to the engine's master table:

```rust
use sea_query::metadata::{MasterTable, metadata_for_table, column::{Name as ColName, Type}, table::Name as TableName};
assert_eq!(
  Query::select()
    .from(metadata_for_table(Users::Table))
    .column(ColName)
    .column(Type)
    .order_by((Name, Asc))
    .to_string(),
  r#(SELECT name from pragma_table_info(('users')) order by name;)#
);

assert_eq!(
  Query::select()
    .from(MasterTable)
    .column(TableName)
    .order_by(TableName)
    .to_string(),
  r#(SELECT name from sqlite_master order by name)#
);
```

## Additional Information

https://stackoverflow.com/questions/1227921/portable-sql-to-determine-if-a-table-exists-or-not
https://stackoverflow.com/a/50548508

**Comment by tyt2y3** [comment]
I think you are looking for https://github.com/SeaQL/sea-schema/blob/master/src/probe.rs
