### ISSUE TITLE
Using `Iden` with `sqlx` is cumbersome

### ISSUE THREAD

**Issue by nitnelave** [SeaQL/sea-query#484]
## Motivation

When writing `sqlx` queries, to avoid using raw strings for column identifiers, the best way to write it is:

```rust
let query = Query::select()
    .from(Users::Table)
    .column(Users::Name)
    .to_string(SqliteQueryBuilder);

let names = sqlx::query(&query)
    .map(|row| row.get::<String, _>(&*Users::Name.to_string()))
    .fetch_all(&pool);
```

I'm mainly focusing on the `&*Users::Name.to_string()` part, which essentially resolves to `"name"`. Could we have a simpler way to express that, especially since they are often derived from enums?

## Proposed Solutions

If we want to keep `Iden` a potentially dynamic trait, then how about adding a new trait `StaticIden : Iden` that has a `.as_str()` method returning a `&'static str`? Then this could be implemented by the `#[derive(Iden)]` macro transparently, or we could add a `#[derive(StaticIden)]`.

Actually if we get `StaticIden` to implement `Into<&'static str>` then I'm sure I could convince `sqlx` devs to accept an `Into<&str>` rather than a `&str` for `row.get`, letting us write the much more elegant `row.get::<String, _>(Users::Name)`.

## Additional Information

[`sqlx::Row::get`](https://docs.rs/sqlx/latest/sqlx/trait.Row.html#method.get)

**Comment by ikrivosheev** [comment]
@nitnelave hello! Thank you for the issue! Why we need new trait? Can we add a new method to `Iden`: `fn as_str(self) -> &'static str`?

**Comment by ikrivosheev** [comment]
And I thin is better `AsRef<str>` then `Into<&str>`

**Comment by nitnelave** [comment]
Adding a method would be a breaking change, that could disrupt anyone who implemented `Iden` based on non-static strings. There's no fundamental requirement that `Iden` instances are not dynamic, so it could be impossible to implement generally.

And +1 for `AsRef<str>`

**Comment by phungleson** [comment]
Hey peeps, as this requires changes in sqlx, an easier stopgap solution is to add a trait like this (not necessary part of `sea-query`).

```
pub trait TryGetIden {
    fn try_get_iden<'a, T: Type<sqlx::Postgres> + Decode<'a, sqlx::Postgres>>(
        &'a self,
        iden: &impl Iden,
    ) -> Result<T, sqlx::Error>;
}
```

Then you can do like this `pg_row.try_get_iden(&Users::Name)`

**Comment by billy1624** [comment]
Hey @phungleson, I don't think `impl AsRef<str> for Iden` requires changing SQLx

**Comment by phungleson** [comment]
Hey @billy1624 thanks,

From the description in `sqlx#2158`, it looks like `try_get` does not yet accept `AsRef<str>` due to sealed trait `ColumnIndex`.

Maybe rust does some coercion or something? In this case, it is probably worth noting down for other people to follow?

**Comment by nitnelave** [comment]
Having `Iden` implement `AsRef<str>` would already simplify the column
reference, it's a good first step. If we can in addition get sqlx to accept
it, it would be great, but having it already implemented in the sea-query
side would be a nice argument in favor.

**Comment by tyt2y3** [comment]
> Having `Iden` implement `AsRef<str>`

I agree this would be a great addition

**Comment by tyt2y3** [comment]
On the other hand, `IdenStatic` exists in SeaORM, and the macro systems impl both Iden and IdenStatic at the same time.
So you can actually derive some SeaORM entities and use their `Column`. 

https://docs.rs/sea-orm/latest/sea_orm/entity/trait.IdenStatic.html

**Comment by nitnelave** [comment]
That's adding a pretty hefty dependency for a small trait :)

**Comment by tyt2y3** [comment]
I am trying to convince you otherwise, if you turn off all default features, sea-orm is not actually that hefty, depending on how you weigh it. I think moving the trait to sea-query is simple, but moving the derive macro is not.
