### ISSUE TITLE
Negating an empty condition results in a syntax error

### ISSUE THREAD

**Issue by nitnelave** [SeaQL/sea-query#485]
## Description

```rust
assert_eq!(Query::select()
    .from(Users::Table)
    .column(Users::Name)
    .cond_where(Cond::all().not())
    .to_string(SqliteQueryBuilder),
    r#"SELECT name FROM users WHERE NOT ()"#
);
```

The empty `Cond::all()` gets translated to `""` instead of a syntactically valid statement.

`all()` should get represented as `SimpleExpr::Value(true)`, and `any()` as `SimpleExpr::Value(false)`.

**Comment by ikrivosheev** [comment]
@nitnelave hello! I opened PR.
