### ISSUE TITLE
Unnecessary heap allocations

### ISSUE THREAD

**Issue by billy1624** [SeaQL/sea-query#490]
I'm wonder why we need `SeaRc<Box<T>>`? Wouldn't `SeaRc<T>` be enough?

https://github.com/SeaQL/sea-query/blob/4ffffeb3378eef9415312515c4cb4399c0072fee/src/table/column.rs#L51

CC @tyt2y3 @ikrivosheev

**Comment by ikrivosheev** [comment]
@billy1624 yes! You are right!

**Comment by ikrivosheev** [comment]
@billy1624, hello! Done: https://github.com/SeaQL/sea-query/pull/492
