### ISSUE TITLE
union does not add parentheses to the individual selects

### ISSUE THREAD

**Issue by adrian-budau** [SeaQL/sea-query#495]
## Steps to Reproduce

1. Create two selectstatements on the same table (cake)
2. First one should be a simple select statement
3. Second should have both a join (cake_filling) and an order by on a column from the joined table
4. Union them

### Expected Behavior

`SELECT cake.column FROM cake (UNION SELECT cake.column FROM cake INNER JOIN cake_filling ON cake.id = cake_filling.cake_id ORDER BY cake_filling.filling_id)`

### Actual Behavior

`SELECT cake.column FROM cake UNION SELECT cake.column FROM cake INNER JOIN cake_filling ON cake.id = cake_filling.cake_id ORDER BY cake_filling.filling_id` which will error:

Error 1250(42000): Table `cake_filling` from one of the SELECTs cannot be used in field list.

### Reproduces How Often

Always on Mysql (That I Tested), but I think it's a problem on all database flavours.

## Versions

0.27.1

## Additional Information

I triggered it in personal code so I don't have an example, could make one if needed.

**Comment by adrian-budau** [comment]
Would you mind if I tried to tackle this and do a PR?

**Comment by ikrivosheev** [comment]
> Would you mind if I tried to tackle this and do a PR?

@adrian-budau hello, yes! We are welcome for a contribution)
