### ISSUE TITLE
Need value 'FullOuterJoin' in 'JoinType' enum

### ISSUE THREAD

**Issue by itsAmitGoyani** [SeaQL/sea-query#496]
## Motivation

I was working with Join query and found that 'Join' and 'InnerJoin' works exactly same. Apart from that I want to use 'FULL JOIN' and there is no such enum value in 'JoinType' enum.

## Proposed Solutions

Add one new value named 'FullOuterJoin' in 'JoinType' enum and also make required changes in query builder.

**Comment by ikrivosheev** [comment]
@itsAmitGoyani hello! Thank you for the issue. I created PR.

**Comment by billy1624** [comment]
Thanks!! @ikrivosheev
