### ISSUE TITLE
Support `NULLS NOT DISTINCT`

### ISSUE THREAD

**Issue by dorianim** [SeaQL/sea-query#509]
## Motivation

I have a unique index over two columns, where both columns are nullable. When one column is null, the other column should be unique. This does not work at the moment, as Postgres treats nulls as distinct (`null != null`).

## Proposed Solutions

Add support for the `NULLS NOT DISTINCT` clause.

## Additional Information

[https://modern-sql.com/caniuse/unique-nulls-not-distinct](https://modern-sql.com/caniuse/unique-nulls-not-distinct)

**Comment by billy1624** [comment]
Hey @dorianim, interesting. But seems MySQL and SQLite both do not support `NULLS NOT DISTINCT`. Only Postgres 15+ support such clause.

https://www.postgresql.org/docs/15/release-15.html#id-1.11.6.5.5.3.4

**Comment by dorianim** [comment]
Ah, ok, I didn't know that. Would still be nice to have that for Postgres :)
