### ISSUE TITLE
support auto_increment for uuid on Postgres

### ISSUE THREAD

**Issue by dorianim** [SeaQL/sea-query#512]
## Motivation

I am using uuids for primary keys to prevent iteration. This comes with the annoyance, that I always have to generate an uuid explicitly when creating an entry.

## Proposed Solutions

Postgres supports [gen_random_uuid()](https://www.postgresql.org/docs/current/functions-uuid.html). This could be used in conjunction with `.auto:increment()` to let the database generate uuids.

An alternative would be to support passing the `gen_random_uuid()` function as the default.

**Comment by ikrivosheev** [comment]
@dorianim hello! I created pr: https://github.com/SeaQL/sea-query/pull/530

**Comment by dorianim** [comment]
Cool! The example is for a select statement, does it also work for insert?

**Comment by ikrivosheev** [comment]
> Cool! The example is for a select statement, does it also work for insert?

Yes, of course. And also for default value.

**Comment by dorianim** [comment]
Nice!
