### ISSUE TITLE
[sqlite] regression: invalid parentheses with UNION/INTERSECT

### ISSUE THREAD

**Issue by evgeniy-terekhin** [SeaQL/sea-query#514]
[this PR](https://github.com/SeaQL/sea-query/pull/498) introduced regression for sqlite
it renders parentheses around UNION/INTERSECT right arg. however it is illegal syntax in sqlite

```
sqlite> select 1 union all (select 1);
Parse error: near "(": syntax error
  select 1 union all (select 1);
                     ^--- error here
```

**Comment by evgeniy-terekhin** [comment]
just to support my claim here is an issue from some other repo
https://github.com/kayak/pypika/issues/537

**Comment by billy1624** [comment]
Hey @evgeniy-terekhin, thanks for the bug report!

I think we can remove the parentheses around select statement after `UNION` operators. Some testing on [Postgres](https://dbfiddle.uk/w1jOjJ_2), [MySQL](https://dbfiddle.uk/LDY1THwo), [MariaDB](https://dbfiddle.uk/KwKBxFzy) and [SQLite](https://dbfiddle.uk/nSgjzhV6).

The source code:

https://github.com/SeaQL/sea-query/blob/28cf151b0cc92318fa701e31ec115c52c05dcace/src/backend/query_builder.rs#L122-L133

**Comment by evgeniy-terekhin** [comment]
@billy1624 please consider the linked fie
