### ISSUE TITLE
`DISTINCT` within Postgres' aggregate functions?

### ISSUE THREAD

**Issue by not-my-profile** [SeaQL/sea-query#518]
How can I build a query such as `SELECT json_agg(DISTINCT some_column) FROM some_table`?

I know that for `json_agg` I can use `Func::cust() -> Expr` ... to add the argument I want to use `Expr::arg` but that expects an `Into<SimpleExpr>` and I cannot quite figure out how to build a `SimpleExpr` from `DISTINCT` and my column `Iden`.
While there is `Expr::cust_with_values` an identifier isn't a value and there is no `Expr::cust_with_exprs`.

**Comment by ikrivosheev** [comment]
@not-my-profile hello! I created PR: https://github.com/SeaQL/sea-query/pull/531.
