### ISSUE TITLE
About dynamic query

### ISSUE THREAD

**Issue by Jacobbishopxy** [SeaQL/sea-query#54]
Hi, I'm a heavy TypeORM user, so it's great to see something similar in Rust! Here I have a quick question, while in `Query::Select()` will you support dynamic '.column()' and '.from()' in the future? 

e.g.:
```rs
Query::select()
    // Instead of using an `enum`, is it possible to use a `String`?
    .column(Char::Character)
    .from(Char::Table)
    .conditions(
        ...
    );
```

**Comment by billy1624** [comment]
You can create `Iden` at runtime with `Alias::new()`

Example:
```rust
use std::rc::Rc;
use sea_query::{*, tests_cfg::*};

let table_as: Rc<dyn Iden> = Rc::new(Alias::new("char"));

let query = Query::select()
    .from_as(Char::Table, table_as.clone())
    .table_column(table_as.clone(), Char::Character)
    .to_owned();
```
https://docs.rs/sea-query/0.11.1/sea_query/query/struct.SelectStatement.html#examples-9

**Comment by Jacobbishopxy** [comment]
Thanks a ton! It works pretty well!  :smile: :smile: :smile:

**Comment by billy1624** [comment]
Welcome :D
