### ISSUE TITLE
Postgres `GEN_RANDOM_UUID`

### ISSUE THREAD

**Issue by billy1624** [SeaQL/sea-query#568]
## Description

This should be `GEN_RANDOM_UUID`

https://github.com/SeaQL/sea-query/blob/46a4170e8167122240a5b4bd662108437af327b1/src/backend/postgres/query.rs#L81

## Additional Information

Test case: https://dbfiddle.uk/VSgTB_Qo

Related PR: https://github.com/SeaQL/sea-query/pull/530

**Comment by tyt2y3** [comment]
Umm most likely a typo, let's do a patch release to 0.28

**Comment by billy1624** [comment]
And we better rename `PgFunction::GetRandomUUID` to `PgFunction::GenRandomUUID`

**Comment by siketyan** [comment]
I have created a small patch for this.
Should we remain get_random_uuid function for backward compatibility? or delete completely?

**Comment by tyt2y3** [comment]
Thank you for the PR. Yes, we have to keep the old function for the patch release but remove it in the next major release.
I'll do it !

**Comment by siketyan** [comment]
@tyt2y3 Thank you! I have allowed editing the PR, so it is ok if you are going to edit the branch directly

**Comment by tyt2y3** [comment]
https://github.com/SeaQL/sea-query/releases/tag/0.28.1 Should fix the problem for now, and your PR would be merged for the next release
