### ISSUE TITLE
Derive macros to support readonly public access to struct

### ISSUE THREAD

**Issue by billy1624** [SeaQL/sea-query#57]
Currently there are no way to read `sea-query` struct directly. Providing readonly access to struct will be necessary to support external crate such as `sea-orm`.

However, this readonly access expose internal data structure to external crate. And internal data structure can be changed over time so external create depending on this readonly access have to understand the risk.

```rust
#[derive(Debug, Clone, ReadOnly)]
pub struct TableCreateStatement {
    pub(crate) table: Option<Rc<dyn Iden>>,
    pub(crate) columns: Vec<ColumnDef>,
    pub(crate) options: Vec<TableOpt>,
    pub(crate) partitions: Vec<TablePartition>,
    pub(crate) indexes: Vec<IndexCreateStatement>,
    pub(crate) foreign_keys: Vec<ForeignKeyCreateStatement>,
    pub(crate) if_not_exists: bool,
}
```

Will generate...

```rust
#[derive(Debug, Clone)]
pub struct ReadOnlyTableCreateStatement {
    pub table: Option<Rc<dyn Iden>>,
    pub columns: Vec<ColumnDef>,
    pub options: Vec<TableOpt>,
    pub partitions: Vec<TablePartition>,
    pub indexes: Vec<IndexCreateStatement>,
    pub foreign_keys: Vec<ForeignKeyCreateStatement>,
    pub if_not_exists: bool,
}
```

Ref: https://internals.rust-lang.org/t/pre-rfc-read-only-visibility/11280

**Comment by tyt2y3** [comment]
I disagree with this approach.

There are two options:
1. define and impl a View trait for accessing data. that hides our internal implementation and is forward compatible.

2. add an addition View method and struct for accessing data.

```rust
fn view() -> &'a MyView;

struct MyView<'a> {
pub columns: &'a Vec<ColumnDef>
}
```

**Comment by billy1624** [comment]
Perhaps we can have something like this?  Getting immutable reference.

```rust
impl TableCreateStatement {
    pub fn get_columns(&self) -> &Vec<ColumnDef> {
        &self.columns
    }
}
```

**Comment by tyt2y3** [comment]
We settle on simple getters for now https://github.com/SeaQL/sea-query/commit/7e102060bd08b5e3e56be6cf650cbead72d2bd70
