### ISSUE TITLE
active_model.update(&db) create the query with `extra space` between 'SET and  WHERE'. 

### ISSUE THREAD

**Issue by grv07** [SeaQL/sea-query#570]
Line of code that does the update:
`let updated_lead = lead_active_model.update(&self.db).await;`

## Versions
sea-orm: "^0"

**Comment by sh-soltanpour** [comment]
Hi @grv07

Can you kindly elaborate more about how to reproduce this and what's your query and database?

I can see in [MySQL](https://github.com/SeaQL/sea-query/blob/master/tests/mysql/query.rs#L1305), [PostgreSQL](https://github.com/SeaQL/sea-query/blob/master/tests/postgres/query.rs#L1400) and [SQLite](https://github.com/SeaQL/sea-query/blob/master/tests/sqlite/query.rs#L1337) test that `WHERE` comes after `SET` and does not have extra space. So I guess that I should do something different to reproduce this issue.

**Comment by ikrivosheev** [comment]
@grv07 hello! Thank you for the report, can you show your query?

**Comment by ikrivosheev** [comment]
@grv07 I close the issues. If the situation repeats, we can open the issue.
