### ISSUE TITLE
Error inserting document containing array in Postgres

### ISSUE THREAD

**Issue by Xenfo** [SeaQL/sea-query#573]
## Description

Generating an insert query (and possibly other types of queries, haven't tested) returns an invalid query. The array is return in values as `VALUES ('{'value'}')` when it should be `VALUES ('{value}')`.

## Steps to Reproduce

1. Generate the insert query
2. Execute it

### Expected Behavior

It should generate a valid insert query but it doesn't.

### Reproduces How Often

Always

## Versions

```
├── sea-query v0.28.1
│   ├── sea-query-attr v0.1.1 (proc-macro)
│   └── sea-query-derive v0.3.0 (proc-macro)
```

## Additional Information

```rs
#[enum_def]
#[derive(Debug, Serialize, Deserialize)]
pub struct RefreshTokenTree {
    pub id: String,
    pub tokens: Vec<String>,
}

Table::create()
            .table(RefreshTokenTreeIden::Table)
            .if_not_exists()
            .col(
                ColumnDef::new(RefreshTokenTreeIden::Id)
                    .string()
                    .not_null()
                    .primary_key(),
            )
            .col(
                ColumnDef::new(RefreshTokenTreeIden::Tokens)
                    .array(ColumnType::String(None))
                    .not_null(),
            )
            .to_string(PostgresQueryBuilder)

Query::insert()
            .into_table(RefreshTokenTreeIden::Table)
            .columns(vec![
                RefreshTokenTreeIden::Id,
                RefreshTokenTreeIden::Tokens,
            ])
            .values_panic(vec![
                self.id.clone().into(),
                self.tokens.clone().into(),
            ])
            .to_string(PostgresQueryBuilder)
```

**Comment by sh-soltanpour** [comment]
Hi everyone,
I'm new to the SeaQL community and I would be more than happy if I work on and fix this issue.

**Comment by tyt2y3** [comment]
> The array is return in values as VALUES ('{'value'}') when it should be VALUES ('{value}').

I don't understand this bit. Can you post a test case ?

Btw, did you turn on the `postgres-array` feature?

**Comment by tyt2y3** [comment]
> Hi everyone, I'm new to the SeaQL community and I would be more than happy if I work on and fix this issue.

Thank you. I think the first step might be to identify the root cause of the problem, and where's the bug. 

I suspect that it's only `to_string` that's wrong, but the general `build` is correct (as we have been using in SeaORM for a while now, it's less-likely to be a bug?)

**Comment by sh-soltanpour** [comment]
> > The array is return in values as VALUES ('{'value'}') when it should be VALUES ('{value}').
> 
> I don't understand this bit. Can you post a test case ?
> 
> Btw, did you turn on the `postgres-array` feature?

@Xenfo Has posted an example on the Discord sea-query channel, I'm just pasting to have it here as well: 

```
let query = refresh_token_tree.query_insert();
    db_pool.get().await.unwrap().execute(query.unwrap().as_str(), &[]).await.unwrap();
```

```
fn query_insert(&self) -> Result<String, Option<ValidationErrors>> {
        Ok(Query::insert()
            .into_table(Alias::new(RefreshTokenTreeIden::Table.to_string().as_str())) // TODO(@Xenfo): use `RefreshTokenTreeIden::Table` once https://github.com/SeaQL/sea-query/issues/533 is fixed
            .columns(vec![
                RefreshTokenTreeIden::Id,
                RefreshTokenTreeIden::Tokens,
            ])
            .values_panic(vec![
                self.id.clone().into(),
                self.tokens.clone().into(),
            ])
            .to_string(PostgresQueryBuilder))
    }
```

```
Table::create()
            .table(Alias::new(RefreshTokenTreeIden::Table.to_string().as_str()))
            .if_not_exists()
            .col(
                ColumnDef::new(RefreshTokenTreeIden::Id)
                    .string()
                    .not_null()
                    .primary_key(),
            )
            .col(
                ColumnDef::new(RefreshTokenTreeIden::Tokens)
                    .array(ColumnType::String(None))
                    .not_null(),
            )
            .to_string(PostgresQueryBuilder)
```

> When inserting the array cockroach doesn't want the '{'val'}' syntax but the '{val}' syntax

**Comment by sh-soltanpour** [comment]
> > Hi everyone, I'm new to the SeaQL community and I would be more than happy if I work on and fix this issue.
> 
> Thank you. I think the first step might be to identify the root cause of the problem, and where's the bug.
> 
> I suspect that it's only `to_string` that's wrong, but the general `build` is correct (as we have been using in SeaORM for a while now, it's less-likely to be a bug?)

 Until now, I've traced the `to_string` method and I suspect that this might be the root of the bug: we should not call the `write_string_quoted` while trying to convert VALUES to string, we should write them as a string without quotes when we face string elements of an array. (I'm still checking if that's the true reason for the bug)

**Comment by Xenfo** [comment]
> Btw, did you turn on the `postgres-array` feature?

Yes I did

**Comment by tyt2y3** [comment]
> Until now, I've traced the `to_string` method and I suspect that this might be the root of the bug: we should not call the `write_string_quoted` while trying to convert VALUES to string, we should write them as a string without quotes when we face string elements of an array. (I'm still checking if that's the true reason for the bug)

I think that's pretty mich it.
