### ISSUE TITLE
Chained add_column statements doesn't work for SQLite

### ISSUE THREAD

**Issue by birwin93** [SeaQL/sea-query#583]
If you have a single alter statement with multiple `add_column` calls, it only executes the first command for SQLite

Code example

```
#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .alter_table(
                sea_query::Table::alter()
                    .table(Users::Table)
                    .add_column_if_not_exists(ColumnDef::new(Users::Name).string())
                    .add_column_if_not_exists(ColumnDef::new(Users::Email).string())
                    .to_owned(),
            )
            .await
}
```

If you execute this with the SQLite driver, only `name` exists. If you switch the order of the `add_column` statements, only the `email` column exists. It works correctly for Postgres though. Only workaround is to just break it into multiple `manage.alter_table` calls

## Steps to Reproduce

Use the above migration with `sqlx-sqlite`

### Expected Behavior

Both `name` and `email` columns are created

### Actual Behavior

Only the first column was created 

### Reproduces How Often

Yes

## Versions

```
│   ├── sea-orm v0.10.2
│   │   ├── sea-orm-macros v0.10.2 (proc-macro)
│   │   ├── sea-query v0.27.1
│   │   │   ├── sea-query-derive v0.2.0 (proc-macro)
│   │   ├── sea-query-binder v0.2.1
│   │   │   ├── sea-query v0.27.1 (*)
│   │   ├── sea-strum v0.23.0
│   │   │   └── sea-strum_macros v0.23.0 (proc-macro)
│   │   │   ├── sea-orm-migration v0.10.2
│   │   │   │   ├── sea-orm v0.10.2 (*)
│   │   │   │   ├── sea-orm-cli v0.10.2
│   │   │   │   │   ├── sea-schema v0.10.2
│   │   │   │   │   │   ├── sea-query v0.27.1 (*)
│   │   │   │   │   │   └── sea-schema-derive v0.1.0 (proc-macro)
│   │   │   │   ├── sea-schema v0.10.2 (*)
│   │   ├── sea-orm v0.10.2 (*)
```

**Comment by ikrivosheev** [comment]
@birwin93 hello! Yes, it is correct behavior because Sqlite doesn't support add multiple columns.

**Comment by ikrivosheev** [comment]
@billy1624 @tyt2y3 maybe we should panic in this situation?

**Comment by tyt2y3** [comment]
Yes throwing an error is better than silence
