### ISSUE TITLE
`TRUNCATE` equivalent in SQLite

### ISSUE THREAD

**Issue by billy1624** [SeaQL/sea-query#587]
SQLite doesn't support `TRUNCATE`. We have to either panic or construct a `DELETE` statement instead.

- Demo: https://dbfiddle.uk/R3QFo6ej

https://github.com/SeaQL/sea-query/blob/03d2a1de32056d126a2e8bfd3c035e9b8cff77e9/src/table/truncate.rs#L7-L28

Ref `TRUNCATE` on all supported DBs:
- https://dbfiddle.uk/gwqzgGGZ
- https://dbfiddle.uk/5QXwOEab
- https://dbfiddle.uk/EI2fujSd
- https://dbfiddle.uk/R3QFo6ej

**Comment by elbertronnie** [comment]
I would like solve this issue. But what should be the prefered method: `panic!` or `DELETE`?
I am new to this codebase so I don't know what is the better trade-off here: "it should only do what I say" or "automatic cross-compatibility".

**Comment by billy1624** [comment]
I think because SeaQuery is a query builder. IMO, we better "only do what I say".

@tyt2y3 please advice!

**Comment by tyt2y3** [comment]
In SeaQuery land the desired behaviour should be error (well for now it's panic)
