### ISSUE TITLE
Missing optional query clause for `cond_where`, like `and_where_option`

### ISSUE THREAD

**Issue by code-mm** [SeaQL/sea-query#59]
Since version `0.12.0` a query with both `and_where` and `and_where_option` specified is not valid anymore. The compilation fails with `` Cannot mix \`and_where`/`or_where` and `cond_where` in statements ``.

The`Condition` struct, accepted by `cond_where`, doesn't have a method to replace `and_where_option` functionality.

**Comment by code-mm** [comment]
Suggesting PR #60 change.

**Comment by tyt2y3** [comment]
Thank you for your report. Yes I overlooked that, and our test cases didn't cover that use case.

**Comment by tyt2y3** [comment]
Fixed on `0.12.2`.
