### ISSUE TITLE
Sending WHERE 1 = 2 causes a invalid byte sequence error.

### ISSUE THREAD

**Issue by AdamJSoftware** [SeaQL/sea-query#591]
## Description
When querying any field and adding a where clause that has "WHERE  1 = 2" but passing in 1 and 2 as args, this causes a invalid byte sequence error to occur

## Steps to Reproduce

Query any field and add this where clause.
```
let rows = client.query("SELECT \"id\" FROM  \"ppm\".\"ppm_database_account\" WHERE $1 = $2", &[&PostgresValue(sea_query::Value::Int(Some(1))), &PostgresValue(sea_query::Value::Int(Some(2)))]).await.unwrap();
```
Query will fail with 
```
thread 'rocket-worker-thread' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlSt
ate(E22021), message: "invalid byte sequence for encoding \"UTF8\": 0x00", detail: None, hint: None, position: None, where_: Some("unnamed portal parameter $1"), schema: None, table: None,
 column: None, datatype: None, constraint: None, file: Some("mbutils.c"), line: Some(1665), routine: Some("report_invalid_encoding") }) }', src/models/database_account/v1_0_0.rs:15:60
stack backtrace:
```

### Expected Behavior

Query doesn't fail

### Actual Behavior

Query does fail

### Reproduces How Often

Everytime

## Versions

```
postgres = { version = "0.19.4", features = ["array-impls", "with-serde_json-1"] }
sea-query = "0.27.2"
sea-query-postgres = "0.1.1"
postgres_array = "0.11.1"
postgres-types = {version="0.2.4", features=["derive"]}
```

**Comment by ikrivosheev** [comment]
@AdamJSoftware hello! Thank you for the issue, but I don't understand where is sea-query? You have mixed sea-query Value and raw query. Why don't you use SeaQuery builder to build Select s query?

**Comment by AdamJSoftware** [comment]
I believe it's the PostgresValue wrappers that are causing the confusion. If I got ahead and just use
```
&[&"1", &"2"]
```
as my params everything works fine.
And I added a raw sql statement because I was trying to do some debugging. Here is the same code but using sea query builder

```
    let (query, args) = Query::select().from((Alias::new("ppm"), Alias::new("ppm_database_account"))).column(Alias::new("id")).and_where(Expr::val(1).eq(2)).build_postgres(PostgresQueryBuilder);
```
Same issue occurs

**Comment by ikrivosheev** [comment]
@AdamJSoftware thank you, now I get it.

**Comment by tyt2y3** [comment]
I think the database schema somehow expect string, not integers. Closing this as I don't think the problem originates in sea-query-binder
