### ISSUE TITLE
Combine sea-query-attr functional with sea-orm model creation

### ISSUE THREAD

**Issue by sergeiivankov** [SeaQL/sea-query#603]
## Motivation

In my case i use https://www.sea-ql.org/SeaORM/docs/generate-entity/entity-structure/ macros for create entity model, it require to model structure must be called `Model`, but if i want use enum_def macro from sea-query, it create Iden enum for this model with Table variant = `model`. So i must use expanded entity structure to combine Model functional with Iden enum for migrations.

## Proposed Solutions

1) Add to enum_def macro argument `table_name` and pass it to macro call, but in this case we must write duplicate table name:
```rust
#[enum_def(table_name = "users")] // <- table name here
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "users")] // <- and table name here
pub struct Model {
```

2) Add new derive macro for sea-query-derive, which will use #[sea_orm] attributes inside, so we can write something like this:
```rust
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, IdenStruct)] // <- new derive macro IdenStruct
#[sea_orm(table_name = "users")] // <- which use #[sea_orm] attribute with table name
pub struct Model {
```

## Additional Information

I have some developments and learn crate sources, so if you accept this proposal, i will create pull request

**Comment by ikrivosheev** [comment]
@sergeiivankov hello! Sorry for delay with an answer. We want to unite `sea-query-attr` and `sea-query-derive`. Related issue: https://github.com/SeaQL/sea-query/issues/533

**Comment by sergeiivankov** [comment]
@ikrivosheev yes, it what i want, thank you!
