### ISSUE TITLE
Correlated subqueries

### ISSUE THREAD

**Issue by bbqsrc** [SeaQL/sea-query#625]
## Motivation

It is sometimes necessary to refer to a field from the surrounding query in a subquery. Here's some SQL as an example

```sql
SELECT t.* FROM transactions t
INNER JOIN transaction_users tu on t.id = tu.transaction_id
WHERE EXISTS (
    SELECT * FROM transaction_users itu
    INNER JOIN users iu on itu.user_id = iu.id
    WHERE itu.transaction_id = t.id
      AND iu.role = 'potato'
);
```

It is not clear to me how to, if it is already possible, to provide the `t.id` to the `EXISTS` subquery using sea-query.

**Comment by ikrivosheev** [comment]
@bbqsrc, you need something like this: `Expr::col((Alias::new("t"), Alias::new("id")))`
