### ISSUE TITLE
Postgres does not have "datetime" column type

### ISSUE THREAD

**Issue by billy1624** [SeaQL/sea-query#71]
I believe the "datetime" column type equivalence is "timestamp without time zone" in Postgres.

Ref: https://www.postgresql.org/docs/13/datatype-datetime.html

Code changes needed here

https://github.com/SeaQL/sea-query/blob/744a8a859fda2b05b471e88500036ef3b8d92798/src/backend/postgres/table.rs#L60-L63

**Comment by tyt2y3** [comment]
Yes, I think `timestamp` is the correct one
