### ISSUE TITLE
CaseStatement has no aggregate functions

### ISSUE THREAD

**Issue by gitmalong** [SeaQL/sea-query#713]
How can I aggregate the SUM over the result of an CASE expression? I found there are no aggregate functions such as `count` or `sum` when building a CaseStatement.

https://docs.rs/sea-query/latest/sea_query/query/struct.CaseStatement.html

https://github.com/SeaQL/sea-query/pull/304/files#diff-8f5819aa8f1164e24c550b1dbe468b3fd76da938b9c19e8c17144d64ad463733R993

In plain postgres SQL I would do: 
```sql
SUM(
     CASE WHEN years_passed IS NOT NULL
     THEN gain_loss ELSE CAST(0 AS DECIMAL) END
) 
AS my_val
```

**Comment by gitmalong** [comment]
I found I can make it work by wrapping `Func::sum()` around

**Comment by tyt2y3** [comment]
@gitmalong thanks for posting this. Would you mind posting the full snippet, that other might find useful?

Untested off my head:

```rust
Func::sum(Expr::case(..).finally(..))
```
