### ISSUE TITLE
sea-query's implementation for .limit(1) destroys performance on pg 12

### ISSUE THREAD

**Issue by sartak** [SeaQL/sea-query#720]
## Description

This is a weird one, but I've ruled everything else out. Using sea-query's `.limit(1)` triggers a ridiculously slow path in Postgres (at least in v12).

## Steps to Reproduce

1. Use a query with a `.limit(1)` on Pg 12
2. Replace `.limit(1)` with `format!("{query} LIMIT 1")`
3. Observe your query speeds up

### Expected Behavior

`.limit(1)` should have indistinguishable performance characteristics from a hardcoded `LIMIT 1`

### Actual Behavior

`.limit(1)` causes a slow path in Postgres, due to using a bind parameter `PostgresValue(BigUnsigned(Some(1)))`.

### Reproduces How Often

Every time. My query looks like:

```
SELECT "main"."foo", "secondary"."bar"
FROM "main"
LEFT JOIN "secondary" ON "main"."secondary" = "secondary"."id"
WHERE "secondary"."baz" = $1
AND "main"."id" <> $2
AND "main"."foo" LIKE $3
ORDER BY "main"."id" DESC
LIMIT $4
```

And my dataset looks like:

```
select count(*) from main left join secondary on secondary.id = main.secondary;
 531206
```

Replacing that `LIMIT $4` by dropping the call to `.limit(1)`, then hackily string-appending `LIMIT 1` to the query produces the following results:

```
Benchmark 1: hardcode
  Time (mean ± σ):      21.0 ms ±   1.8 ms    [User: 3.9 ms, System: 1.9 ms]
  Range (min … max):    19.7 ms …  26.3 ms    50 runs

Benchmark 2: bind
  Time (mean ± σ):      81.0 ms ±  10.7 ms    [User: 3.9 ms, System: 2.0 ms]
  Range (min … max):    69.0 ms … 109.4 ms    50 runs

Summary
  'hardcode' ran
    3.86 ± 0.61 times faster than 'bind'
```

## Versions

```
λ cargo tree | g sea-
│   ├── sea-query v0.30.2
│   │   ├── sea-query-derive v0.4.1 (proc-macro)
│   ├── sea-query-rusqlite v0.4.0
│   │   └── sea-query v0.30.2 (*)
├── sea-query v0.30.2 (*)
├── sea-query-postgres v0.4.0
│   └── sea-query v0.30.2 (*)
├── sea-query-rusqlite v0.4.0 (*)
```

PostgreSQL 12.16 (Ubuntu 12.16-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit

Linux redacted 5.4.0-166-generic #183-Ubuntu SMP Mon Oct 2 11:28:33 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu 20.04.3 LTS (focal)

## Additional Information

Since the parameter to `.limit()` is a `u64`, there's no security risk to unconditionally inlining it. The two issues I see here are compat (as always), and inlining would cause different limit sizes on otherwise identical queries to produce extra `prepare_cached` entries. But the tradeoff seems worth it here given that impact is way worse than extra prepares.

If changing how `.limit(1)` stringifies is a nonstarter, then could you instead add a `limit_expr` method like exists for `order_by` vs `order_by_expr`? That way I can do `.limit_expr(Expr::cust(1))` to recover performance, rather than this messy `format!("{query} LIMIT 1")`.

**Comment by tyt2y3** [comment]
Interesting finding. Can you try hacking the limit parameter to i32 and see if it makes a difference?

**Comment by sartak** [comment]
Using an inline `LIMIT 1::bigint` appears to be just as fast as `LIMIT 1`.

> Can you try hacking the limit parameter to i32 and see if it makes a difference?

Changing `fn limit` to take a `u32` or `i32` (which bind as `PostgresValue(Int(Some(1)))`) instead of a `u64` both throw `db error: ERROR: insufficient data left in message` errors at query time. I'm not sure how to proceed from here, since I don't know the pg wire protocol at all. I'm using tokio-postgres.

> Also, by inspecting the query plan may be it can show the difference?

The query plans are the same, but the bind parameter version takes noticeably longer to run.

```
[2023-11-21T23:12:36Z DEBUG tokio_postgres::prepare] preparing query s19: EXPLAIN ANALYZE SELECT "main"."foo", "secondary"."bar" FROM "main" LEFT JOIN "secondary" ON "main"."secondary" = "secondary"."id" WHERE "secondary"."baz" = $1 AND "main"."id" <> $2 AND "main"."foo" LIKE $3 ORDER BY "main"."id" DESC LIMIT $4
[2023-11-21T23:12:36Z DEBUG tokio_postgres::query] executing statement s19 with parameters: [PostgresValue(Int(Some(1))), PostgresValue(Int(Some(2))), PostgresValue(String(Some("…%"))), PostgresValue(BigUnsigned(Some(1)))]
Limit  (cost=9360.02..9360.02 rows=1 width=52) (actual time=27.572..29.240 rows=1 loops=1)
  ->  Sort  (cost=9360.02..9360.02 rows=1 width=52) (actual time=27.572..29.239 rows=1 loops=1)
        Sort Key: main.id DESC
        Sort Method: quicksort  Memory: 25kB
        ->  Gather  (cost=1000.42..9360.01 rows=1 width=52) (actual time=27.546..29.232 rows=1 loops=1)
              Workers Planned: 2
              Workers Launched: 2
              ->  Nested Loop  (cost=0.42..8359.91 rows=1 width=52) (actual time=19.423..25.389 rows=0 loops=3)
                    ->  Parallel Seq Scan on main  (cost=0.00..8267.04 rows=11 width=41) (actual time=19.417..25.383 rows=0 loops=3)
                          Filter: ((id <> 2) AND (foo ~~ '…%'::text))
                          Rows Removed by Filter: 177068
                    ->  Index Scan using secondary_pkey on secondary  (cost=0.42..8.44 rows=1 width=19) (actual time=0.014..0.014 rows=1 loops=1)
                          Index Cond: (id = main.secondary)
                          Filter: (baz = 1)
Planning Time: 0.290 ms
Execution Time: 29.262 ms
```

```
[2023-11-21T23:13:35Z DEBUG tokio_postgres::prepare] preparing query s8: EXPLAIN ANALYZE SELECT "main"."foo", "secondary"."bar" FROM "main" LEFT JOIN "secondary" ON "main"."secondary" = "secondary"."id" WHERE "secondary"."baz" = $1 AND "main"."id" <> $2 AND "main"."foo" LIKE $3 ORDER BY "main"."id" DESC LIMIT 1
[2023-11-21T23:13:35Z DEBUG tokio_postgres::query] executing statement s8 with parameters: [PostgresValue(Int(Some(1))), PostgresValue(Int(Some(2))), PostgresValue(String(Some("…%")))]
Limit  (cost=9360.02..9360.02 rows=1 width=52) (actual time=19.164..21.209 rows=1 loops=1)
  ->  Sort  (cost=9360.02..9360.02 rows=1 width=52) (actual time=19.163..21.208 rows=1 loops=1)
        Sort Key: main.id DESC
        Sort Method: quicksort  Memory: 25kB
        ->  Gather  (cost=1000.42..9360.01 rows=1 width=52) (actual time=19.096..21.200 rows=1 loops=1)
              Workers Planned: 2
              Workers Launched: 2
              ->  Nested Loop  (cost=0.42..8359.91 rows=1 width=52) (actual time=13.098..17.258 rows=0 loops=3)
                    ->  Parallel Seq Scan on main  (cost=0.00..8267.04 rows=11 width=41) (actual time=13.092..17.252 rows=0 loops=3)
                          Filter: ((id <> 2) AND (foo ~~ '…%'::text))
                          Rows Removed by Filter: 177068
                    ->  Index Scan using secondary_pkey on secondary  (cost=0.42..8.44 rows=1 width=19) (actual time=0.015..0.015 rows=1 loops=1)
                          Index Cond: (id = main.secondary)
                          Filter: (baz = 1)
Planning Time: 0.281 ms
Execution Time: 21.221 ms
```

**Comment by sartak** [comment]
I tried writing up a repro but not quite there yet, the query plan is coming out very different and so the results of the two variants are essentially identical. But I figure I'd share what I have so far for completeness.

```
$ docker run -it ubuntu:focal bash
# apt update && apt install -y postgresql curl build-essential
# service postgresql start
# echo "CREATE USER test WITH PASSWORD 'test'; CREATE DATABASE test OWNER test" | su postgres -c psql
# curl https://sh.rustup.rs -sSf | sh -s -- --profile minimal -y
# source "$HOME/.cargo/env"
# cargo new app
# cd app
# cargo add rand postgres sea-query sea-query-postgres
# curl 'https://gist.githubusercontent.com/sartak/31cb58e9e43429696533094b5f55c93b/raw/089967e5258dff408c375476ab087afdca2c69c2/main.rs' -o src/main.rs
# cargo run
```

**Comment by tyt2y3** [comment]
It might be parallel to what you've been doing, but can you try this against a later version of Postgres? Like 13, 14 etc. I am just trying to understand if the problem you're seeing is version specific.

**Comment by sartak** [comment]
The `.limit(1)` slowdown affects pg 12.16 and 12.17. Upgrading to 16 fixed it though. Feel free to close since I no longer need `limit_expr` I suppose. ¯\\\_(ツ)\_/¯

**Comment by tyt2y3** [comment]
Got you
