### ISSUE TITLE
Postgres `TIMESTAMP WITH TIMEZONE` (`TIMESTAMPTZ`) support

### ISSUE THREAD

**Issue by ShawnROGrady** [SeaQL/sea-query#75]
Currently there is only a `Value::DateTime` variant which does not work for `TIMESTAMP WITH TIMEZONE` (`TIMESTAMPTZ`) column types.

**Comment by billy1624** [comment]
Hi, thanks for the issue! What is your suggestions on this?

Perhaps we can add `Value::DateTimeTz` that is timezone aware?

```rust
pub enum Value {
    #[cfg(feature = "with-chrono")]
    DateTimeTz(Box<chrono::DateTime>),
    // ...
}

```

**Comment by ShawnROGrady** [comment]
@billy1624 hi, that was my initial thought but I wasn't sure how well that would translate across the other dialects you support (mysql, sqlite) since postgres is what I'm most familiar with. Adding an additional enum variant seems like the clearest solution to me assuming other dialects have something analogous to `TIMESTAMPTZ`.

Thanks!

**Comment by billy1624** [comment]
Yes, @ShawnROGrady, good point! We have to also consider the `TIMESTAMPTZ` support on other databases.

**Comment by billy1624** [comment]
> Currently there is only a `Value::DateTime` variant which does not work for `TIMESTAMP WITH TIMEZONE` (`TIMESTAMPTZ`) column types.

The problem is that `Value::DateTime` will produce a datetime string that does not have timezone suffix? i.e. "2021-07-27 16:48:00".

However, what you need for updating / inserting a `TIMESTAMPTZ` column is something like "2021-07-27 16:48:00+08"?

Correct me if I am wrong. Thanks!!

Ref: https://www.postgresql.org/docs/9.1/datatype-datetime.html

**Comment by tyt2y3** [comment]
@billy1624 I think your understanding of the problem is correct.

**Comment by tyt2y3** [comment]
I suggest adding a variant to `Value` called `DateTimeWithTimeZone`

**Comment by forrest-akin** [comment]
Similarly, `Time` is missing a corresponding `TimeTz`

**Comment by tyt2y3** [comment]
[`0.12.9`](https://github.com/SeaQL/sea-query/releases/tag/0.12.9)
@ShawnROGrady please re-open this issue if you find any issues.
@forrest-akin please open a new issue if you needed that.
