### ISSUE TITLE
rusqlite - bundled forces static linkage 

### ISSUE THREAD

**Issue by majorfrog** [SeaQL/sea-query#754]
## Description

sea-query-rusqlite dependency rusqlite, states feature "bundled" which forces static linkage and automatically compile and link in an up to date version of SQLite.

It is not  a default feature (for good reasons) and increases the binary size significantly. 

It shopuld not be the default or it should be possible to state whether or not you want this behavior. 

### Expected Behavior

Should be possible to link against already present version of sqlite on the system. 

### Actual Behavior

Sqlite is built and statically linked. 

### Reproduces How Often

Always

## Versions
 sea-orm v0.12.10
 sea-query v0.30.6

## Additional Information

Dependency in
sea-query-rusqlite/Cargo.toml

**Comment by tyt2y3** [comment]
A PR would be appreciated to make it an optional feature.

**Comment by tyt2y3** [comment]
Fixed in https://crates.io/crates/sea-query-rusqlite/0.6.0-rc.1
