### ISSUE TITLE
Support postgres arrays

### ISSUE THREAD

**Issue by Fuuzetsu** [SeaQL/sea-query#76]
It seems that there's completely no mention of postgres arrays. They are documented at https://www.postgresql.org/docs/9.1/arrays.html

My current work-around is something like:
```rust
pub struct PostgresArrayOf(sea_query::ColumnType);

impl sea_query::Iden for PostgresArrayOf {
    fn unquoted(&self, s: &mut dyn std::fmt::Write) {
        let mut sqlw = sea_query::SqlWriter::new();
        sea_query::PostgresQueryBuilder.prepare_column_type(&self.0, &mut sqlw);
        write!(s, "{}[]", sqlw.result()).unwrap();
    }
}
// snip…
ColumnDef::new(RunResult::Parameters)
                .not_null()
                .custom(PostgresArrayOf(sea_query::ColumnType::Double(None)))
```

**Comment by Fuuzetsu** [comment]
Ah, but it seems that while we can make custom type here, it doesn't seem to be possible to insert into it afterwards...

**Comment by billy1624** [comment]
Hi @Fuuzetsu, thanks for raising this issue. Can I also know the insert / update syntax for array values in Postgres?

**Comment by Fuuzetsu** [comment]
> Hi @Fuuzetsu, thanks for raising this issue. Can I also know the insert / update syntax for array values in Postgres?

The link I posted already describes the syntax: curly braves with postgres delimiter (comma, I guess).

**Comment by tyt2y3** [comment]
I am sorry this feature is not in our plan. A PR is welcome, but we will not be able to work on it.
Please close this issue if you can't allocate effort to work on it either.
Thank you for your support!

**Comment by Fuuzetsu** [comment]
I see. I switched to `diesel` instead which has support for all the [postgres-specific stuff](https://docs.rs/diesel/1.4.7/diesel/pg/types/sql_types/index.html).

I hope one day sea-query will have such support too and I could switch back but it's not worth the investment of time to do myself for our simple use-case.
