### ISSUE TITLE
Postgres `binary` Type

### ISSUE THREAD

**Issue by forrest-akin** [SeaQL/sea-query#77]
The mapping for `ColumnType::Binary` in [`PostgresQueryBuilder.prepare_column_type()`](https://github.com/SeaQL/sea-query/blob/9a8806221a1392302faea00dc49fd513457d0ee8/src/backend/postgres/table.rs#L73) maps to a `binary` type. This doesn't appear to map to any documented type in postgres (see [Table 8.1 Data Types](https://www.postgresql.org/docs/current/datatype.html#DATATYPE-TABLE)). It's unclear if this is a mistake or just an undocumented type alias (pg mentions there are undocumented type aliases). Could this be updated to use a documented type? Since this takes an optional `length`, maybe this is meant to be `bit`? Possibly `bytea`, but that doesn't take a `length`.

**Comment by tyt2y3** [comment]
Yes you are right. I think bytea is the intended type name.

**Comment by tyt2y3** [comment]
[0.12.9](https://github.com/SeaQL/sea-query/releases/tag/0.12.9)
