### ISSUE TITLE
sea-query-binder has time version `<0.3.35`

### ISSUE THREAD

**Issue by jeremychone** [SeaQL/sea-query#772]
## Description

In `sea-query-binder` version `0.6.0-rc.2`,

in sea-query-binder, the `time` crate version is set as `<0.3.35` (i.e., `time = { version = "<0.3.35",...}`).

Is there any reason for this?

It does cause some understandably unforeseen behavior when the lib/app code relies on `0.3`.
It seems to work, but tools like `cargo outdated` completely break for example, and might have other side effects. 

## Steps to Reproduce

1. Have sea-query with sea-query-binder with time
2. have another `time = "0.3'` in the `Cargo.toml`
3. `cargo install cargo-outdated` and then `cargo outdated`. The issue is that if this break, there might be more side effecs. 

### Expected Behavior

`time` set to version  `0.3` or `0.3.35`.

### Actual Behavior

`time` set to version  `<0.3.35`.

## Versions

In `sea-query-binder` version `0.6.0-rc.2`,

**Comment by tyt2y3** [comment]
See https://github.com/SeaQL/sea-query/pull/766
