### ISSUE TITLE
Missing Expr::tbl

### ISSUE THREAD

**Issue by ctron** [SeaQL/sea-query#779]
In the documentation (https://www.sea-ql.org/SeaORM/docs/advanced-query/custom-joins/) there is an example of `Expr::tbl`, which seems to be missing.

```rust
        .column_as(
            Expr::tbl(Alias::new("fruit_alias"), fruit::Column::Name).into_simple_expr(),
            "fruit_name"
        )
```

I assume either the documentation or the code needs an update.

**Comment by tyt2y3** [comment]
Edited
