### ISSUE TITLE
Align ColumnType and Value variants

### ISSUE THREAD

**Issue by forrest-akin** [SeaQL/sea-query#78]
It would be nice to have the expected mappings from [database types](https://www.postgresql.org/docs/current/datatype.html#DATATYPE-TABLE) to [Value](https://docs.rs/sea-query/0.12.8/sea_query/value/enum.Value.html) types, similar to [sqlx](https://docs.rs/sqlx/0.5.5/sqlx/postgres/types/index.html#types). It's been challenging figuring out which `Value` variant I need to construct when setting a default value for a column in a table schema based on a dynamic column type, especially since there isn't a one-to-one mapping of [`ColumnType`](https://docs.rs/sea-query/0.12.8/sea_query/table/enum.ColumnType.html) to Value.

**Comment by tyt2y3** [comment]
You usually do not have to specify the Value variant manually. The intended usage is `into`, e.g.
```rust
let v: Value = 123.into();
```

It is the underlying driver's responsibility to bind the respective value type to the binary protocol. So yes, if you are using SQLx as driver, you'd look at it's documentation. The responsibility of the `Value` enum is only to hold the query parameters temporarily until it's time for prepare. 

So yes, there is not a one-to-one mapping for column type to value type. For example, when comparing a value with a decimal column, you can using any numeric values.

I agree that could be a bit confusing though. At what scenario you need specify the variant manually?

**Comment by forrest-akin** [comment]
My use case is dynamically generating `CREATE TABLE` statements so based on the column type I need to know what rust type to cast the input to before converting to a `Value`. So you're right, I'm not constructing `Value` variants manually (I'm using `Value::from`), but I do need to know which rust type to cast to based on the column type.
