### ISSUE TITLE
Introduce `md5` SQL function

### ISSUE THREAD

**Issue by IgnisDa** [SeaQL/sea-query#785]
## Motivation

I would like to call the MD5 SQL function. Both Postgres and MySQL have support for it and have the same function signature. SQLite does not have support.

## Proposed Solutions

Right now I am using `Func::custom`.

## Additional Information

I am willing to make a PR.

**Comment by IgnisDa** [comment]
@billy1624 @tyt2y3 I made a PR for the same. Can you take a look?

**Comment by RichardWGNR** [comment]
The idea is good, but it is not good to create a function for every sneeze. Instead, you can create your own implementation of Func:: or use macros.

Otherwise, the code base will be clogged with functions supported in one DBMS but not supported in another.

**Comment by IgnisDa** [comment]
@RichardWGNR I'm already using Function::cust but how can this be done with macros? Using Function::cust makes the code very verbose.
