### ISSUE TITLE
Allow using sqlx 0.8.1 with sea-query-binder

### ISSUE THREAD

**Issue by sandhose** [SeaQL/sea-query#809]
## Motivation

sqlx 0.8.1 got out a week ago with no breaking API change, but `sea-query-binder` sets the dependency to `<0.8.1`

## Proposed Solutions

Relax the requirement to `<0.9.0`, so that we keep compatibility with old version, but still trust sqlx for not doing API-breaking changes in patch versions

## Additional Information

–

**Comment by Jupp56** [comment]
To add: sqlx 0.8.1 fixes a [security vulnerability](https://rustsec.org/advisories/RUSTSEC-2024-0363.html). This is actually an important update, I think.

**Comment by billy1624** [comment]
Just released https://crates.io/crates/sea-query-binder/0.7.0-rc.2
