### ISSUE TITLE
Support Table `CHECK` Constraints

### ISSUE THREAD

**Issue by forrest-akin** [SeaQL/sea-query#84]
Currently, there's no way to specify table constraints in [`TableCreateStatement`](https://docs.rs/sea-query/0.12.8/sea_query/table/struct.TableCreateStatement.html#)s. Adding an `.extra()` method similar to [`ColumnDef`](https://docs.rs/sea-query/0.12.8/sea_query/table/struct.ColumnDef.html#method.extra) would probably be the easiest way to add support for this.

**Comment by billy1624** [comment]
You can specify unique, primary key and reference constraints with `index`, `primary_key` and `foreign_key` methods in `TableCreateStatement`.

**Comment by billy1624** [comment]
However, yesterday I discovered the generated unique constraint SQL statement for Postgres is incorrect. There will be an excess "KEY" keyword in the statement.

**Comment by billy1624** [comment]
You can checkout this example, https://github.com/SeaQL/sea-schema/blob/e284b5b72c098f3afab5600f848245fa28127927/tests/live/postgres/src/main.rs#L75-L162.

**Comment by tyt2y3** [comment]
#85

**Comment by forrest-akin** [comment]
Oops, I meant to specify table _CHECK_ constraints is what's missing. I did run into the unique key issue, but I think the rest is fine as you mentioned.
