### ISSUE TITLE
`UPSERT` statement support

### ISSUE THREAD

**Issue by Progdrasil** [SeaQL/sea-query#88]
In [sqlite] and [postgres], it is possible to use the `ON CONFLICT` clause for `INSERT` statements in order to do an [upsert]

### Example

As an example suppose you have the following table: 
```sql
CREATE TABLE customers (
	customer_id serial PRIMARY KEY,
	name VARCHAR UNIQUE,
	email VARCHAR NOT NULL,
	active bool NOT NULL DEFAULT TRUE
);
```

and you wish to insert without having errors and it is safe to update if it already exists in the table, this can all be handled in sql in the following way:
```sql
INSERT INTO customers (name, email)
VALUES('Microsoft','hotline@microsoft.com') 
ON CONFLICT (name) 
DO 
   UPDATE SET email = EXCLUDED.email;
```

_Note: all examples are taken directly from the [upsert] link (postgresqltutorial.com)._

[sqlite]: https://sqlite.org/lang_conflict.html
[postgres]: https://www.postgresql.org/docs/13/sql-insert.html#SQL-ON-CONFLICT
[upsert]: https://www.postgresqltutorial.com/postgresql-upsert/

### Api suggestion

This is meant as a suggestion of what could be nice to  have as an api for this, this is by no means what might end up being implemented. It might not be possible to implement as written below.

The clause in both cases has two parameters, a `target` column on which a constraint is generally applied, and a `action`.

```rust
use sea_query::{Query, ConflictAction};

// upsert example
Query::insert()
    .into_table(Customers::Table)
    .columns([Customers::Name, Customers::Email])
    .on_conflict(Customers::Name, ConflictAction::Update(Query::update().set(Customers::Email))

// ignore example
Query::insert()
    .into_table(Customers::Table)
    .columns([Customers::Name, Customers::Email])
    .on_conflict(Customers::Name, ConflictAction::Nothing)
```

### Alternatives

An alternative to supporting the `ON CONFLICT` clause would be to implement the `UPSERT` statement directly which is supported in 
* Postgresql version >= 9.5
* Sqlite version >= 3.24.0 (2018-06-04)
* mysql version >= none

But seeing as `ON CONFLICT` is more powerful and seems to be the best practice in Postgresql anyways. I'm not sure this would be a viable alternative.

### Limitations

Seeing as `ON CONFLICT` is not standard SQL this can lead to issues, namely the fact that [MySql handles upserts differently][mysql]. Where the `ON CONFLICT(target) DO UPDATE` would actually be `ON DUPLICATE KEY UPDATE` and it doesnt seem like you can add a target. The previous was the easy one, the others such as `DO NOTHING` changes the statement entirely to be `INSERT IGNORE ...` I'm not sure how this can be implemented cleanly.

[mysql]: https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html

**Comment by tyt2y3** [comment]
Thank you for coming back. I have not had a conclusion yet. But I am more inclined towards implementing an `UPSERT` statement first.

**Comment by Progdrasil** [comment]
> But I am more inclined towards implementing an `UPSERT` statement first.

Thanks for the welcome. I'll look into how I can implement that when I get some time

**Comment by baoyachi** [comment]
Hi,I'm working for this issue [https://github.com/SeaQL/sea-orm/issues/187](https://github.com/SeaQL/sea-orm/issues/187).

Please Assignees to me.

Maybe the `upsert` api need discuss when i collection what all about  database syntax.

**Comment by Sytten** [comment]
Any progress?

**Comment by billy1624** [comment]
Please check #279. It provides basic support of `ON CONFLICT`
